import { useEffect, useRef, useState } from "react";
import {
  generateQuiz,
  type QuizItem,
} from "../services/api";
import { toastService } from "../services/toastService";
import { QuizCard } from "../components/QuizCard";
import "./QuizPage.css";
// ── Constants ──────────────────────────────────────────────────────────────────


const QUIZ_STORAGE_KEY = "rag.quiz.pending";
// ── Types ──────────────────────────────────────────────────────────────────────


interface QuizState {
  items: QuizItem[];
  projectId: string;
  lessonContent: string;
  numQuestions: number;
  variationSeed?: number | null;
}


// ── Helpers ────────────────────────────────────────────────────────────────────


// ── Export helpers ────────────────────────────────────────────────────────────


/** Download a text blob with the given filename */
function downloadTextFile(content: string, filename: string, mime = "text/plain;charset=utf-8") {
  const blob = new Blob(["\uFEFF" + content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 200);
}


/**
 * Export to Moodle GIFT format (.txt)
 * Spec: https://docs.moodle.org/en/GIFT_format
 * Supports MCQ only (4 options A–D)
 */
export function exportToGift(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "// GIFT format — Generated by RAG Teaching Material",
    "// Import: Moodle > Question Bank > Import > GIFT format",
    "",
  ];
  items.forEach((item, idx) => {
    // Escape special GIFT chars: { } = # ~
    const esc = (s: string) => s.replace(/[{}=#~]/g, "\\$&");
    lines.push(`// Question ${idx + 1}`);
    lines.push(`::Q${idx + 1}:: ${esc(item.question)} {`);
    item.options.forEach((opt) => {
      // opt format: "A. text" or "A) text"
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      const isCorrect = letter === item.correct_answer.toUpperCase();
      // GIFT: = correct, ~ wrong
      const feedback = item.explanations?.[letter]
        ? ` # ${esc(item.explanations[letter])}`
        : "";
      lines.push(`  ${isCorrect ? "=" : "~"}${esc(text)}${feedback}`);
    });
    lines.push(`}`);
    lines.push("");
  });
  return lines.join("\n");
}


/**
 * Export to Moodle Aiken format (.txt)
 * Spec: https://docs.moodle.org/en/Aiken_format
 * Very simple and human-readable format for multiple choice.
 */
export function exportToAiken(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [];
  items.forEach((item) => {
    lines.push(item.question);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`${letter}) ${text}`);
    });
    lines.push(`ANSWER: ${item.correct_answer.toUpperCase()}`);
    lines.push("");
  });
  return lines.join("\n");
}


/**
 * Export to Kahoot-compatible CSV (.csv)
 * Columns: Question, Answer 1, Answer 2, Answer 3, Answer 4, Time limit, Correct answer
 * Correct answer = 1-indexed position of correct option
 */
export function exportToCsv(items: import("../services/api").QuizItem[]): string {
  const header = ["Question", "Answer 1", "Answer 2", "Answer 3", "Answer 4", "Time limit (sec)", "Correct answer"];
  const rows = items.map((item) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    // Pad to 4 answers if needed
    while (opts.length < 4) opts.push("");
    const correctIdx = ["A", "B", "C", "D"].indexOf(item.correct_answer.toUpperCase()) + 1;
    return [
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      "60",
      String(correctIdx),
    ].join(",");
  });
  return [header.join(","), ...rows].join("\n");
}


function inferSubjectPrefix(lessonContent: string): string {
  const content = lessonContent || "";
  const h1Match = content.match(/^#\s+(.+)$/m);
  if (!h1Match) return "QUIZ";
  const title = h1Match[1].trim();
  if (/scrum/i.test(title)) return "SCRUM";
  if (/project\s+management|quản\s+lý\s+dự\s+án/i.test(title)) return "PM";
  if (/software\s+engineering|công\s+nghệ\s+phần\s+mềm/i.test(title)) return "SE";
  const cleanTitle = title.replace(/^(?:Chương|Chuong|Chapter)\s+\d+[:.\s]*/i, "").trim();
  const normalized = cleanTitle
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[đĐ]/g, "d");
  const words = normalized.split(/\s+/).filter(w => w.length > 0);
  if (words.length === 1) {
    return words[0].substring(0, 4).toUpperCase();
  }
  

  return words
    .map(w => w[0])
    .join("")
    .replace(/[^A-Za-z0-9]/g, "")
    .toUpperCase()
    .substring(0, 5);
}


function generateQuestionCode(
  subjectPrefix: string,
  chapterName: string,
  bloomLevel: string,
  index: number
): string {
  let sub = (subjectPrefix || "QUIZ").trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!sub) sub = "QUIZ";
  let chNo = "CH00";
  const chMatch = chapterName.match(/(?:Chương|Chuong|Chapter)\s*(\d+)/i);
  if (chMatch) {
    chNo = `CH${chMatch[1].padStart(2, "0")}`;
  } else {
    const anyNum = chapterName.match(/\d+/);
    if (anyNum) {
      chNo = `CH${anyNum[0].padStart(2, "0")}`;
    }
  }


  const bloomMap: Record<string, string> = {
    "Nhận biết": "NB",
    "Thông hiểu": "TH",
    "Vận dụng": "VD",
    "Vận dụng cao": "VC",
  };
  const bl = bloomMap[bloomLevel] || "GEN";
  const idxStr = String(index).padStart(3, "0");
  return `${sub}_${chNo}_${bl}_${idxStr}`;
}


export function exportToStandardBankCsv(items: import("../services/api").QuizItem[], lessonContent: string): string {
  const header = [
    "QuestionCode",
    "Chapter",
    "Topic",
    "BloomLevel",
    "Difficulty",
    "Question",
    "OptionA",
    "OptionB",
    "OptionC",
    "OptionD",
    "CorrectAnswer",
    "Explanation"
  ];
  const bloomMap: Record<string, string> = {
    knowledge: "Nhận biết",
    comprehension: "Thông hiểu",
    application: "Vận dụng",
    analysis: "Vận dụng cao"
  };
  const subjectPrefix = inferSubjectPrefix(lessonContent);
  const rows = items.map((item, idx) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    while (opts.length < 4) opts.push("");
    const bloomLevel = bloomMap[item.type] || "Nhận biết";
    const chapterName = item.chapter || "Chương chung";
    const topicName = item.topic || "Chung";
    const difficultyName = item.difficulty || "Dễ";
    const qCode = generateQuestionCode(subjectPrefix, chapterName, bloomLevel, idx + 1);
    return [
      `"${qCode}"`,
      `"${chapterName.replace(/"/g, "\"\"")}"`,
      `"${topicName.replace(/"/g, "\"\"")}"`,
      `"${bloomLevel.replace(/"/g, "\"\"")}"`,
      `"${difficultyName.replace(/"/g, "\"\"")}"`,
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      `"${item.correct_answer.toUpperCase()}"`,
      `"${item.explanation.replace(/"/g, "\"\"")}"`,
    ].join(",");
  });
  return [header.join(","), ...rows].join("\n");
}


/**
 * Export to Printable Text Format (.txt)
 */
/**
 * Export to Markdown format (.md)
 */
export function exportToMarkdown(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "# Ngân hàng câu hỏi trắc nghiệm",
    "",
    "Tài liệu tự động tạo bởi hệ thống hỗ trợ giảng dạy AI.",
    "",
    "---",
    ""
  ];
  items.forEach((item, idx) => {
    lines.push(`### Câu ${idx + 1}: ${item.question}`);
    lines.push("");
    item.options.forEach((opt) => {
      lines.push(`- ${opt}`);
    });
    lines.push("");
    lines.push(`**Đáp án đúng:** ${item.correct_answer.toUpperCase()}`);
    lines.push("");
    if (item.explanation) {
      lines.push(`**Giải thích:** ${item.explanation}`);
    }
    if (item.chapter || item.topic || item.difficulty) {
      lines.push("");
      lines.push("#### Metadata:");
      if (item.chapter) lines.push(`- **Chương:** ${item.chapter}`);
      if (item.topic) lines.push(`- **Chủ đề:** ${item.topic}`);
      if (item.difficulty) lines.push(`- **Độ khó:** ${item.difficulty}`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  });
  return lines.join("\n");
}


export function exportToPrintableTxt(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "==================================================",
    "                BÀI KIỂM TRA TRẮC NGHIỆM ĐỀ BẢN IN",
    "==================================================",
    "",
    "Họ và tên:...................................................... Lớp:...................",
    "Ngày làm bài:...../...../.........",
    "",
    "--------------------------------------------------",
    "PHẦN I: ĐỀ BÀI (Chọn đáp án đúng nhất)",
    "--------------------------------------------------",
    "",
  ];
  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: ${item.question}`);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`   ${letter}. ${text}`);
    });
    lines.push("");
  });
  lines.push("==================================================");
  lines.push("               ĐÁP ÁN VÀ HƯỚNG DẪN GIẢI");
  lines.push("==================================================");
  lines.push("");
  lines.push("BẢNG ĐÁP ÁN:");
  const answerKeyRow: string[] = [];
  items.forEach((item, idx) => {
    answerKeyRow.push(`Câu ${idx + 1}: ${item.correct_answer}`);
  });
  for (let i = 0; i < answerKeyRow.length; i += 5) {
    lines.push(answerKeyRow.slice(i, i + 5).join("   |   "));
  }
  lines.push("CHI TIẾT GIẢI THÍCH:");
  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: Đáp án đúng: ${item.correct_answer}`);
    if (item.explanations) {
      lines.push(`- Giải thích chi tiết các lựa chọn:`);
      Object.entries(item.explanations).forEach(([choice, exp]) => {
        lines.push(`  + Lựa chọn ${choice}: ${exp}`);
      });
    } else {
      lines.push(`- Giải thích: ${item.explanation}`);
    }
    if (item.restudy_hint) {
      lines.push(`- Gợi ý ôn tập: ${item.restudy_hint}`);
    }
    lines.push("");
  });
  return lines.join("\n");
}


export function exportToMoodleXml(items: import("../services/api").QuizItem[]): string {
  const escapeXml = (unsafe: string) => {
    return unsafe.replace(/[<>&'"]/g, (c) => {
      switch (c) {
        case '<': return '&lt;';
        case '>': return '&gt;';
        case '&': return '&amp;';
        case '\'': return '&apos;';
        case '"': return '&quot;';
        default: return c;
      }
    });
  };

  const xmlParts: string[] = [];
  xmlParts.push('<?xml version="1.0" encoding="UTF-8"?>');
  xmlParts.push('<quiz>');
  
  // Tạo category mặc định cho bộ câu hỏi
  xmlParts.push('  <question type="category">');
  xmlParts.push('    <category>');
  xmlParts.push('      <text>$course$/top/RAG_Generated_Quiz</text>');
  xmlParts.push('    </category>');
  xmlParts.push('  </question>');
  xmlParts.push('');

  items.forEach((item, idx) => {
    const qName = `Câu ${idx + 1}`;
    xmlParts.push('  <!-- question: ' + (idx + 1) + ' -->');
    xmlParts.push('  <question type="multichoice">');
    xmlParts.push(`    <name>`);
    xmlParts.push(`      <text>${escapeXml(qName)}</text>`);
    xmlParts.push(`    </name>`);
    
    xmlParts.push('    <questiontext format="html">');
    xmlParts.push(`      <text><![CDATA[${item.question}]]></text>`);
    xmlParts.push('    </questiontext>');
    
    if (item.explanation) {
      xmlParts.push('    <generalfeedback format="html">');
      xmlParts.push(`      <text><![CDATA[${item.explanation}]]></text>`);
      xmlParts.push('    </generalfeedback>');
    }
    
    xmlParts.push('    <defaultgrade>1.0000000</defaultgrade>');
    xmlParts.push('    <penalty>0.3333333</penalty>');
    xmlParts.push('    <hidden>0</hidden>');
    xmlParts.push('    <single>true</single>');
    xmlParts.push('    <shuffleanswers>true</shuffleanswers>');
    xmlParts.push('    <answernumbering>abc</answernumbering>');
    
    xmlParts.push('    <correctfeedback format="html">');
    xmlParts.push('      <text><![CDATA[Câu trả lời của bạn là đúng.]]></text>');
    xmlParts.push('    </correctfeedback>');
    xmlParts.push('    <partiallycorrectfeedback format="html">');
    xmlParts.push('      <text><![CDATA[Câu trả lời của bạn là đúng một phần.]]></text>');
    xmlParts.push('    </partiallycorrectfeedback>');
    xmlParts.push('    <incorrectfeedback format="html">');
    xmlParts.push('      <text><![CDATA[Câu trả lời của bạn là sai.]]></text>');
    xmlParts.push('    </incorrectfeedback>');

    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      const isCorrect = letter === item.correct_answer.toUpperCase();
      const fraction = isCorrect ? 100 : 0;
      
      xmlParts.push(`    <answer fraction="${fraction}" format="html">`);
      xmlParts.push(`      <text><![CDATA[${text}]]></text>`);
      
      const optFeedback = item.explanations?.[letter] || "";
      xmlParts.push('      <feedback format="html">');
      xmlParts.push(`        <text><![CDATA[${optFeedback}]]></text>`);
      xmlParts.push('      </feedback>');
      xmlParts.push('    </answer>');
    });

    xmlParts.push('  </question>');
    xmlParts.push('');
  });

  xmlParts.push('</quiz>');
  return xmlParts.join('\n');
}


function getNextIdNumber(existingItems: import("../services/api").QuizItem[]): number {
  let max = 0;
  existingItems.forEach((item) => {
    const match = item.id.match(/^q(\d+)$/);
    if (match) {
      const num = parseInt(match[1], 10);
      if (num > max) max = num;
    }
  });
  return max + 1;
}


const textToNumberMap: Record<string, number> = {
  "mot": 1, "một": 1, "one": 1,
  "hai": 2, "two": 2,
  "ba": 3, "three": 3,
  "bon": 4, "bốn": 4, "tu": 4, "tư": 4, "four": 4,
  "nam": 5, "năm": 5, "five": 5,
  "sau": 6, "sáu": 6, "six": 6,
  "bay": 7, "bảy": 7, "bẩy": 7, "seven": 7,
  "tam": 8, "tám": 8, "eight": 8,
  "chin": 9, "chín": 9, "nine": 9,
  "muoi": 10, "mười": 10, "ten": 10,
  "muoi mot": 11, "mười một": 11, "eleven": 11,
  "muoi hai": 12, "mười hai": 12, "twelve": 12,
  "muoi ba": 13, "mười ba": 13, "thirteen": 13,
  "muoi bon": 14, "mười bốn": 14, "muoi tu": 14, "mười tư": 14, "fourteen": 14,
  "muoi nam": 15, "mười năm": 15, "fifteen": 15,
  "muoi sau": 16, "mười sáu": 16, "sixteen": 16,
  "muoi bay": 17, "mười bảy": 17, "mười bẩy": 17, "seventeen": 17,
  "muoi tam": 18, "mười tám": 18, "eighteen": 18,
  "muoi chin": 19, "mười chín": 19, "nineteen": 19,
  "hai muoi": 20, "hai mươi": 20, "twenty": 20
};

function getQuestionsCountFromPrompt(prompt: string): number {
  const cleanPrompt = (prompt || "").trim().toLowerCase();
  if (!cleanPrompt) return 5;
  
  // 1. Kiểm tra ký tự số trước "câu/cau/question" (ví dụ: "3 câu", "12 câu")
  const digitMatch = cleanPrompt.match(/(\d+)\s*(?:câu|cau|question)/i);
  if (digitMatch) {
    const num = parseInt(digitMatch[1], 10);
    if (num >= 1 && num <= 20) return num;
  }
  
  // 2. Kiểm tra chữ viết số trước "câu/cau/question" (ví dụ: "ba câu", "mười lăm câu")
  const numberWords = Object.keys(textToNumberMap).join("|");
  const wordRegex = new RegExp(`\\b(${numberWords})\\s*(?:câu|cau|question)`, "i");
  const wordMatch = cleanPrompt.match(wordRegex);
  if (wordMatch) {
    const word = wordMatch[1];
    const num = textToNumberMap[word];
    if (num && num >= 1 && num <= 20) return num;
  }
  
  // 3. Fallback: tìm ký tự số hoặc chữ viết số tự do bất kỳ đâu trong prompt
  const digitAnywhere = cleanPrompt.match(/\b(\d+)\b/);
  if (digitAnywhere) {
    const num = parseInt(digitAnywhere[1], 10);
    if (num >= 1 && num <= 20) return num;
  }
  
  const wordRegexAnywhere = new RegExp(`\\b(${numberWords})\\b`, "i");
  const wordMatchAnywhere = cleanPrompt.match(wordRegexAnywhere);
  if (wordMatchAnywhere) {
    const word = wordMatchAnywhere[1];
    const num = textToNumberMap[word];
    if (num && num >= 1 && num <= 20) return num;
  }

  return 5; // default fallback
}


// ── QuizPage ───────────────────────────────────────────────────────────────────


export default function QuizPage() {
  const [items, setItems] = useState<QuizItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [progressVal, setProgressVal] = useState(0);
  const [error, setError] = useState("");
  const [projectId, setProjectId] = useState("");
  const [lessonContent, setLessonContent] = useState("");
  const [numQuestions, setNumQuestions] = useState(5);
  const [variationSeed, setVariationSeed] = useState<number | null>(null);
  const [activeCard, setActiveCard] = useState<number | null>(null);
  const [showExportMenu, setShowExportMenu] = useState(false);
  // Modal settings
  const [showRegenModal, setShowRegenModal] = useState(false);
  const [regenCustom, setRegenCustom] = useState("");
  const [showQuizPromptGuide, setShowQuizPromptGuide] = useState(false);
  const initCalledRef = useRef(false);
  // ── Init ──────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (initCalledRef.current) return;
    initCalledRef.current = true;
    try {
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (!raw)
        throw new Error(
          "Không tìm thấy dữ liệu quiz. Vui lòng quay lại bài giảng.",
        );
      const state: QuizState = JSON.parse(raw);
      setProjectId(state.projectId || "");
      setLessonContent(state.lessonContent || "");
      setNumQuestions(state.numQuestions || 5);
      // If we already have items and seed in the storage, use them
      if (state.items && state.items.length > 0) {
        setItems(state.items);
        setVariationSeed(state.variationSeed ?? null);
        setLoading(false);
        return;
      }

      // Otherwise, instead of auto-generating, just enter setup mode
      setLoading(false);
      setShowRegenModal(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Lỗi tải dữ liệu quiz.");
      setLoading(false);
    }
  }, []);
  // Sanitize and clamp numQuestions when opening configuration modal to prevent 422 errors
  useEffect(() => {
    if (showRegenModal) {
      if (numQuestions > 20 || numQuestions < 1) {
        setNumQuestions(5);
      }
    }
  }, [showRegenModal, numQuestions]);
  // ── Handlers ──────────────────────────────────────────────────────────────


  const handleBack = () => {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      window.close();
      if (projectId) {
        window.location.href = `/materials/${projectId}/editor`;
      } else {
        window.location.href = "/";
      }
    }
  };
  const handleUpdateItem = (updatedItem: QuizItem) => {
    const newItems = items.map((q) => (q.id === updatedItem.id ? updatedItem : q));
    setItems(newItems);
    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
        }),
      );
    }
  };
  const handleDeleteItem = (questionId: string) => {
    const newItems = items.filter((q) => q.id !== questionId);
    setItems(newItems);
    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
        }),
      );
    }
  };
  const handleRegenerate = (n: number, bloom: string, custom: string, mode: "replace" | "append" = "replace") => {
    const cleanContent = (lessonContent || "").trim();
    if (!cleanContent) {
      toastService.warning("Nội dung bài giảng của mục này đang trống. Vui lòng quay lại Soạn thảo bài giảng để tạo nội dung trước!");
      return;
    }

    const placeholderTexts = [
      "chay ai tao hoac nhap noi dung markdown thu cong",
      "chạy ai tạo hoặc nhập nội dung markdown thủ công",
      "ban xem truoc trong",
      "bản xem trước trống"
    ];
    const normContent = cleanContent.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[đĐ]/g, "d");
    const isPlaceholder = placeholderTexts.some(p => normContent.includes(p));

    const lines = cleanContent.split("\n").map(l => l.trim()).filter(Boolean);
    const bodyLines = lines.filter(l => !l.startsWith("#"));
    const bodyText = bodyLines.join("\n").trim();

    if (isPlaceholder || !bodyText || bodyText.length < 15) {
      toastService.warning("Mục này chưa được soạn thảo nội dung lý thuyết chi tiết. Vui lòng tạo nội dung bài giảng trước khi tạo quiz!");
      return;
    }

    const newSeed = Math.floor(Math.random() * 10000);
    const nextIdStart = getNextIdNumber(items);
    setLoading(true);
    setProgressVal(0);
    setError("");
    setShowRegenModal(false);
    const interval = setInterval(() => {
      setProgressVal((prev) => {
        if (prev >= 95) return prev;
        const increment = prev < 50 ? Math.floor(Math.random() * 6) + 4 : Math.floor(Math.random() * 2) + 1;
        return Math.min(prev + increment, 95);
      });
    }, 450);
    generateQuiz(lessonContent, n, newSeed, bloom, custom)
      .then((res) => {
        clearInterval(interval);
        setProgressVal(100);
        setTimeout(() => {
          const generatedQuestions = res.questions ?? [];
          let newItems: QuizItem[];
          if (mode === "append") {
            const mappedQuestions = generatedQuestions.map((q, idx) => ({
              ...q,
              id: `q${nextIdStart + idx}`
            }));
            newItems = [...items, ...mappedQuestions];
          } else {
            newItems = generatedQuestions;
          }

          setItems(newItems);
          setNumQuestions(n);
          setVariationSeed(res.variation_seed ?? newSeed);
          setLoading(false);
          // Update localStorage with the new questions
          const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
          if (raw) {
            const state = JSON.parse(raw);
            localStorage.setItem(
              QUIZ_STORAGE_KEY,
              JSON.stringify({
                ...state,
                numQuestions: n,
                items: newItems,
                variationSeed: res.variation_seed ?? newSeed,
              }),
            );
          }
        }, 300);
      })
      .catch((err: any) => {
        clearInterval(interval);
        let msg = "Lỗi tạo quiz.";
        if (err.response?.data?.detail) {
          const detail = err.response.data.detail;
          if (typeof detail === "string") msg = detail;
          else if (typeof detail === "object" && detail.message) msg = detail.message;
        } else if (err.message) {
          msg = err.message;
        }
        setError(msg);
        setLoading(false);
      });
  };
  // ── Derived state ─────────────────────────────────────────────────────────
  const visibleItems = items;
  // ── Loading / Error ────────────────────────────────────────────────────────


  if (loading) {
    return (
      <div className="qp-page" style={{ background: "#ffffff", display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh" }}>
        <div className="qp-center" style={{ width: "100%", maxWidth: "360px", padding: 24, textAlign: "center", background: "#ffffff", borderRadius: 16, border: "1px solid #e2e8f0", boxShadow: "0 10px 30px rgba(0,0,0,0.08)" }}>
          <div className="qp-spinner" style={{ margin: "0 auto 16px", borderColor: "#f1f5f9", borderTopColor: "#4f46e5" }} />
          <p style={{ color: "#0f172a", fontSize: 16, margin: "0 0 8px 0", fontWeight: 700 }}>
            Đang tạo câu hỏi quiz... ({progressVal}%)
          </p>
          <div style={{ height: 6, width: "100%", background: "#f1f5f9", borderRadius: 3, overflow: "hidden", marginBottom: 12 }}>
            <div 
              style={{ height: "100%", background: "linear-gradient(90deg, #4f46e5, #6366f1)", width: `${progressVal}%`, borderRadius: 3, transition: "width 0.2s ease-out" }}
            />
          </div>
          <p style={{ color: "#64748b", fontSize: 12, margin: 0 }}>
            Gemini đang phân tích nội dung bài giảng và thiết kế câu hỏi trắc nghiệm
          </p>
        </div>
      </div>
    );
  }


  if (error) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div style={{ fontSize: 52 }}>⚠️</div>
          <div className="qp-error" style={{ maxWidth: 440 }}>
            <p style={{ margin: 0, color: "#fca5a5", fontWeight: 600 }}>{error}</p>
            <button className="qp-btn-primary" onClick={handleBack}>
              ← Quay lại
            </button>
          </div>
        </div>
      </div>
    );
  }


  // ── Render ─────────────────────────────────────────────────────────────────


  return (
    <div className="qp-page">
      {/* Header */}
      <header className="qp-header">
        <button className="qp-back-btn" onClick={handleBack}>
          ← Quay lại
        </button>
        <div className="qp-header-center">
          <h1 className="qp-header-title">📝 Xem trước ngân hàng câu hỏi</h1>
          {variationSeed !== null && (
            <span className="qp-seed-badge">seed #{variationSeed}</span>
          )}
        </div>
        <div className="qp-header-right">
          <button
            className="qp-regen-btn"
            onClick={() => setShowRegenModal(true)}
            title="Tạo bộ câu hỏi mới"
          >
            🔀 Câu hỏi mới
          </button>
          {/* Export dropdown — only when questions are loaded */}
          {items.length > 0 && (
            <div style={{ position: "relative" }}>
              <button
                className="qp-regen-btn"
                style={{ background: "#0f766e", borderColor: "#0d9488", color: "#ffffff" }}
                onClick={() => setShowExportMenu((v) => !v)}
                title="Xuất câu hỏi ra file để dùng trên LMS"
              >
                ⬇ Xuất Quiz
              </button>
              {showExportMenu && (
                <div
                  style={{
                    position: "absolute",
                    top: "calc(100% + 8px)",
                    right: 0,
                    background: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: "16px",
                    padding: "12px",
                    zIndex: 50,
                    width: "350px",
                    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.02)",
                    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
                  }}
                  onMouseLeave={() => setShowExportMenu(false)}
                >
                  <p style={{ margin: "0 4px 12px 4px", fontSize: "11px", color: "#64748b", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase" }}>
                    📤 Xuất ngân hàng câu hỏi
                  </p>
                  <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                    {/* Item 1: CSV (.csv) - Recommended / Primary */}
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        padding: "12px",
                        background: "rgba(59, 130, 246, 0.04)",
                        borderRadius: "12px",
                        cursor: "pointer",
                        border: "1px solid rgba(59, 130, 246, 0.15)",
                        transition: "all 0.2s ease-in-out",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = "rgba(59, 130, 246, 0.08)";
                        e.currentTarget.style.borderColor = "rgba(59, 130, 246, 0.25)";
                        e.currentTarget.style.transform = "translateY(-1px)";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = "rgba(59, 130, 246, 0.04)";
                        e.currentTarget.style.borderColor = "rgba(59, 130, 246, 0.15)";
                        e.currentTarget.style.transform = "none";
                      }}
                      onClick={() => {
                        downloadTextFile(exportToStandardBankCsv(items, lessonContent), "ngan_hang_cau_hoi.csv", "text/csv;charset=utf-8");
                        setShowExportMenu(false);
                      }}
                    >
                      <div style={{ fontSize: "18px", display: "flex", alignItems: "center", justifyContent: "center", width: "36px", height: "36px", background: "rgba(56, 189, 248, 0.15)", borderRadius: "10px", color: "#38bdf8" }}>
                        ⭐
                      </div>
                      <div style={{ flex: 1, minWidth: 0, textAlign: "left" }}>
                        <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                          <span style={{ fontSize: "13px", fontWeight: 700, color: "#1e293b" }}>CSV (.csv)</span>
                          <span style={{ fontSize: "9px", fontWeight: 700, padding: "2px 6px", background: "#3b82f6", color: "#ffffff", borderRadius: "12px", textTransform: "uppercase", letterSpacing: "0.02em" }}>Định dạng chính</span>
                        </div>
                        <p style={{ margin: "2px 0 0 0", fontSize: "11px", color: "#64748b", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>Ngân hàng câu hỏi đầy đủ</p>
                      </div>
                    </div>
                    {/* Item 2: Moodle GIFT */}
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        padding: "12px",
                        background: "#f8fafc",
                        borderRadius: "12px",
                        cursor: "pointer",
                        border: "1px solid #e2e8f0",
                        transition: "all 0.2s ease-in-out",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = "#f1f5f9";
                        e.currentTarget.style.borderColor = "#cbd5e1";
                        e.currentTarget.style.transform = "translateY(-1px)";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = "#f8fafc";
                        e.currentTarget.style.borderColor = "#e2e8f0";
                        e.currentTarget.style.transform = "none";
                      }}
                      onClick={() => {
                        downloadTextFile(exportToGift(items), "quiz_moodle_gift.txt");
                        setShowExportMenu(false);
                      }}
                    >
                      <div style={{ fontSize: "18px", display: "flex", alignItems: "center", justifyContent: "center", width: "36px", height: "36px", background: "rgba(249, 115, 22, 0.15)", borderRadius: "10px", color: "#f97316" }}>
                        📘
                      </div>
                      <div style={{ flex: 1, minWidth: 0, textAlign: "left" }}>
                        <span style={{ fontSize: "13px", fontWeight: 700, color: "#334155" }}>GIFT (.txt)</span>
                        <p style={{ margin: "2px 0 0 0", fontSize: "11px", color: "#64748b", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>Import trực tiếp vào Moodle (LMS)</p>
                      </div>
                    </div>
                    {/* Item 2.5: Moodle XML */}
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        padding: "12px",
                        background: "#f8fafc",
                        borderRadius: "12px",
                        cursor: "pointer",
                        border: "1px solid #e2e8f0",
                        transition: "all 0.2s ease-in-out",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = "#f1f5f9";
                        e.currentTarget.style.borderColor = "#cbd5e1";
                        e.currentTarget.style.transform = "translateY(-1px)";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = "#f8fafc";
                        e.currentTarget.style.borderColor = "#e2e8f0";
                        e.currentTarget.style.transform = "none";
                      }}
                      onClick={() => {
                        downloadTextFile(exportToMoodleXml(items), "ngan_hang_cau_hoi.xml", "text/xml;charset=utf-8");
                        setShowExportMenu(false);
                      }}
                    >
                      <div style={{ fontSize: "18px", display: "flex", alignItems: "center", justifyContent: "center", width: "36px", height: "36px", background: "rgba(168, 85, 247, 0.15)", borderRadius: "10px", color: "#a855f7" }}>
                        🔮
                      </div>
                      <div style={{ flex: 1, minWidth: 0, textAlign: "left" }}>
                        <span style={{ fontSize: "13px", fontWeight: 700, color: "#334155" }}>Moodle XML (.xml)</span>
                        <p style={{ margin: "2px 0 0 0", fontSize: "11px", color: "#64748b", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>Định dạng import chuẩn của Moodle</p>
                      </div>
                    </div>
                    {/* Item 3: Markdown */}
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        padding: "12px",
                        background: "#f8fafc",
                        borderRadius: "12px",
                        cursor: "pointer",
                        border: "1px solid #e2e8f0",
                        transition: "all 0.2s ease-in-out",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = "#f1f5f9";
                        e.currentTarget.style.borderColor = "#cbd5e1";
                        e.currentTarget.style.transform = "translateY(-1px)";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = "#f8fafc";
                        e.currentTarget.style.borderColor = "#e2e8f0";
                        e.currentTarget.style.transform = "none";
                      }}
                      onClick={() => {
                        downloadTextFile(exportToMarkdown(items), "ngan_hang_cau_hoi.md");
                        setShowExportMenu(false);
                      }}
                    >
                      <div style={{ fontSize: "18px", display: "flex", alignItems: "center", justifyContent: "center", width: "36px", height: "36px", background: "rgba(16, 185, 129, 0.15)", borderRadius: "10px", color: "#10b981" }}>
                        📝
                      </div>
                      <div style={{ flex: 1, minWidth: 0, textAlign: "left" }}>
                        <span style={{ fontSize: "13px", fontWeight: 700, color: "#334155" }}>Markdown (.md)</span>
                        <p style={{ margin: "2px 0 0 0", fontSize: "11px", color: "#64748b", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>Chỉnh sửa, xem trước và lưu trữ</p>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </header>
      {/* Main content */}
      <div className="qp-content">
        {/* Question cards */}
        {visibleItems.map((item, idx) => (
          <div key={item.id} id={`quiz-card-${items.indexOf(item)}`}>
            <QuizCard
              item={item}
              index={items.indexOf(item)}
              userAnswer={undefined}
              submitted={false}
              expanded={activeCard === idx}
              onSelect={() => {}}
              onToggleExpand={(i) => setActiveCard(activeCard === i ? null : i)}
              onUpdateItem={handleUpdateItem}
              onDeleteItem={handleDeleteItem}
            />
          </div>
        ))}
      </div>
      {/* Regen Modal */}
      {showRegenModal && (
        <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <div style={{ background: "#fff", padding: "24px", borderRadius: "12px", width: "100%", maxWidth: "480px", boxShadow: "0 20px 40px rgba(0,0,0,0.2)" }}>
            <h2 style={{ margin: "0 0 16px 0", fontSize: 20 }}>{items.length === 0 ? "Cấu hình Quiz" : "Tạo Quiz mới"}</h2>
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: "block", marginBottom: 8, fontSize: 14, fontWeight: 600 }}>Nhập yêu cầu tạo câu hỏi (Prompt)</label>
              <textarea 
                spellCheck={false}
                value={regenCustom} 
                onChange={e => {
                  setRegenCustom(e.target.value);
                  e.target.style.height = "auto";
                  e.target.style.height = `${e.target.scrollHeight}px`;
                }}
                placeholder="Nhập yêu cầu chi tiết để tạo câu hỏi hiệu quả"
                style={{ width: "100%", padding: "10px 12px", borderRadius: "8px", border: "1px solid #cbd5e1", minHeight: "42px", height: "auto", resize: "none", fontSize: 13, lineHeight: "1.5" }}
              />
            </div>
            <div style={{ fontSize: "12px", color: "#475569", background: "#f8fafc", padding: "12px", borderRadius: "8px", marginBottom: 20, border: "1px solid #e2e8f0", lineHeight: "1.6" }}>
              <div 
                onClick={() => setShowQuizPromptGuide(!showQuizPromptGuide)}
                style={{ 
                  color: "#0f172a", 
                  fontWeight: 700, 
                  cursor: "pointer", 
                  display: "flex", 
                  alignItems: "center", 
                  justifyContent: "space-between",
                  userSelect: "none"
                }}
              >
                <span>💡 Cách prompt đạt hiệu quả cao nhất</span>
                <span style={{ fontSize: "10px", color: "#64748b" }}>{showQuizPromptGuide ? "▼" : "▶"}</span>
              </div>
              {showQuizPromptGuide && (
                <div style={{ marginTop: 8 }} className="animate-in fade-in duration-200">
                  <ul style={{ margin: "0 0 8px 0", paddingLeft: "16px", display: "flex", flexDirection: "column", gap: "2px" }}>
                    <li>Nêu rõ số lượng cụ thể (VD: <em>"tạo 3 câu..."</em>, <em>"5 câu..."</em>).</li>
                    <li>Nêu rõ Chương/Mục kiểm tra (VD: <em>"về Chương 1"</em>, <em>"Mục 2.1"</em>).</li>
                    <li>Nêu rõ mức độ Bloom mong muốn (<em>Nhận biết</em>, <em>Thông hiểu</em>, <em>Vận dụng</em>, <em>Vận dụng cao</em>).</li>
                  </ul>
                  <div style={{ borderTop: "1px solid #e2e8f0", paddingTop: "6px", fontSize: "11px", color: "#64748b" }}>
                    <strong>Ví dụ đầy đủ:</strong> <em>"Tạo 5 câu hỏi nâng cao mức độ Nhận biết và Thông hiểu về các khái niệm cốt lõi trong Mục 1.1 Công nghệ phần mềm."</em>
                  </div>
                  <div style={{ marginTop: "8px", borderTop: "1px dashed #fca5a5", paddingTop: "6px", fontSize: "11px", color: "#b91c1c", display: "flex", gap: "4px", alignItems: "flex-start" }}>
                    <span>⚠️</span>
                    <span><strong>Lưu ý quan trọng:</strong> Hệ thống không thể sinh câu hỏi đối với các mục bài giảng chưa được soạn thảo nội dung lý thuyết chi tiết.</span>
                  </div>
                </div>
              )}
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {items.length === 0 ? (
                <div style={{ display: "flex", gap: 10 }}>
                  <button 
                    onClick={() => { setShowRegenModal(false); handleBack(); }}
                    style={{ flex: 1, padding: "10px 16px", borderRadius: "8px", border: "1px solid #cbd5e1", background: "#fff", cursor: "pointer", fontWeight: 600, color: "#475569", fontSize: "13px", textAlign: "center" }}
                  >
                    Quay lại
                  </button>
                  <button 
                    onClick={() => {
                      const n = getQuestionsCountFromPrompt(regenCustom);
                      handleRegenerate(n, "mix", regenCustom, "replace");
                    }}
                    style={{ 
                      flex: 1, 
                      padding: "10px 16px", 
                      borderRadius: "8px", 
                      border: "none", 
                      background: "#4f46e5", 
                      cursor: "pointer", 
                      fontWeight: 600, 
                      color: "#fff", 
                      fontSize: "13px", 
                      textAlign: "center",
                      opacity: !regenCustom.trim() ? 0.6 : 1,
                      pointerEvents: !regenCustom.trim() ? "none" : "auto"
                    }}
                    disabled={!regenCustom.trim()}
                  >
                    ✨ Bắt đầu tạo Quiz
                  </button>
                </div>
              ) : (
                <>
                  <div style={{ display: "flex", gap: 10 }}>
                    <button 
                      onClick={() => {
                        const n = getQuestionsCountFromPrompt(regenCustom);
                        handleRegenerate(n, "mix", regenCustom, "replace");
                      }}
                      style={{ 
                        flex: 1,
                        padding: "10px 12px", 
                        borderRadius: "8px", 
                        border: "none", 
                        background: "#ef4444", 
                        cursor: "pointer", 
                        fontWeight: 600, 
                        color: "#fff",
                        fontSize: "13px",
                        textAlign: "center",
                        opacity: !regenCustom.trim() ? 0.6 : 1,
                        pointerEvents: !regenCustom.trim() ? "none" : "auto"
                      }}
                      title="Xoá tất cả câu hỏi hiện tại và tạo bộ mới"
                      disabled={!regenCustom.trim()}
                    >
                      Tạo mới (Thay thế)
                    </button>
                    <button 
                      onClick={() => {
                        const n = getQuestionsCountFromPrompt(regenCustom);
                        handleRegenerate(n, "mix", regenCustom, "append");
                      }}
                      style={{ 
                        flex: 1,
                        padding: "10px 12px", 
                        borderRadius: "8px", 
                        border: "none", 
                        background: "#10b981", 
                        cursor: "pointer", 
                        fontWeight: 600, 
                        color: "#fff",
                        fontSize: "13px",
                        textAlign: "center",
                        opacity: !regenCustom.trim() ? 0.6 : 1,
                        pointerEvents: !regenCustom.trim() ? "none" : "auto"
                      }}
                      title="Giữ nguyên các câu hỏi hiện tại, chỉ tạo thêm câu hỏi mới gộp vào"
                      disabled={!regenCustom.trim()}
                    >
                      Tạo thêm & Gộp vào ({items.length})
                    </button>
                  </div>
                  <button 
                    onClick={() => setShowRegenModal(false)}
                    style={{ 
                      width: "100%", 
                      padding: "10px 16px", 
                      borderRadius: "8px", 
                      border: "1px solid #cbd5e1", 
                      background: "#fff", 
                      cursor: "pointer", 
                      fontWeight: 600, 
                      color: "#475569",
                      fontSize: "13px",
                      textAlign: "center"
                    }}
                  >
                    Hủy
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}


    </div>
  );
}