import { useEffect, useRef, useState } from "react";
import {
  generateQuiz,
  getQuizStats,
  saveQuizAttempt,
  type QuizItem,
  type QuizStats,
} from "../services/api";
import { QuizCard } from "../components/QuizCard";
import { ScorePanel } from "../components/ScorePanel";
import "./QuizPage.css";

// ── Constants ──────────────────────────────────────────────────────────────────

const QUIZ_STORAGE_KEY = "rag.quiz.pending";

// ── Types ──────────────────────────────────────────────────────────────────────

interface UserAnswers {
  [questionId: string]: string;
}

interface QuizState {
  items: QuizItem[];
  projectId: string;
  lessonContent: string;
  numQuestions: number;
  variationSeed?: number | null;
  answers?: UserAnswers;
  elapsed?: number;
  submitted?: boolean;
  score?: number;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function formatTimer(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${String(m).padStart(2, "00")}:${String(s).padStart(2, "00")}`;
}

// ── Export helpers ────────────────────────────────────────────────────────────

/** Download a text blob with the given filename */
function downloadTextFile(content: string, filename: string, mime = "text/plain;charset=utf-8") {
  const blob = new Blob(["\uFEFF" + content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 200);
}

/**
 * Export to Moodle GIFT format (.txt)
 * Spec: https://docs.moodle.org/en/GIFT_format
 * Supports MCQ only (4 options A–D)
 */
function exportToGift(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "// GIFT format — Generated by RAG Teaching Material",
    "// Import: Moodle > Question Bank > Import > GIFT format",
    "",
  ];
  items.forEach((item, idx) => {
    // Escape special GIFT chars: { } = # ~
    const esc = (s: string) => s.replace(/[{}=#~]/g, "\\$&");
    lines.push(`// Question ${idx + 1}`);
    lines.push(`::Q${idx + 1}:: ${esc(item.question)} {`);
    item.options.forEach((opt) => {
      // opt format: "A. text" or "A) text"
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      const isCorrect = letter === item.correct_answer.toUpperCase();
      // GIFT: = correct, ~ wrong
      const feedback = item.explanations?.[letter]
        ? ` # ${esc(item.explanations[letter])}`
        : "";
      lines.push(`  ${isCorrect ? "=" : "~"}${esc(text)}${feedback}`);
    });
    lines.push(`}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Moodle Aiken format (.txt)
 * Spec: https://docs.moodle.org/en/Aiken_format
 * Very simple and human-readable format for multiple choice.
 */
function exportToAiken(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [];
  items.forEach((item) => {
    lines.push(item.question);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`${letter}) ${text}`);
    });
    lines.push(`ANSWER: ${item.correct_answer.toUpperCase()}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Kahoot-compatible CSV (.csv)
 * Columns: Question, Answer 1, Answer 2, Answer 3, Answer 4, Time limit, Correct answer
 * Correct answer = 1-indexed position of correct option
 */
function exportToCsv(items: import("../services/api").QuizItem[]): string {
  const header = ["Question", "Answer 1", "Answer 2", "Answer 3", "Answer 4", "Time limit (sec)", "Correct answer"];
  const rows = items.map((item) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    // Pad to 4 answers if needed
    while (opts.length < 4) opts.push("");
    const correctIdx = ["A", "B", "C", "D"].indexOf(item.correct_answer.toUpperCase()) + 1;
    return [
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      "60",
      String(correctIdx),
    ].join(",");
  });
  return [header.join(","), ...rows].join("\n");
}

function inferSubjectPrefix(lessonContent: string): string {
  const content = lessonContent || "";
  const h1Match = content.match(/^#\s+(.+)$/m);
  if (!h1Match) return "QUIZ";
  
  const title = h1Match[1].trim();
  
  if (/scrum/i.test(title)) return "SCRUM";
  if (/project\s+management|quản\s+lý\s+dự\s+án/i.test(title)) return "PM";
  if (/software\s+engineering|công\s+nghệ\s+phần\s+mềm/i.test(title)) return "SE";
  
  const cleanTitle = title.replace(/^(?:Chương|Chuong|Chapter)\s+\d+[:.\s]*/i, "").trim();
  
  const normalized = cleanTitle
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[đĐ]/g, "d");
    
  const words = normalized.split(/\s+/).filter(w => w.length > 0);
  if (words.length === 1) {
    return words[0].substring(0, 4).toUpperCase();
  }
  
  return words
    .map(w => w[0])
    .join("")
    .replace(/[^A-Za-z0-9]/g, "")
    .toUpperCase()
    .substring(0, 5);
}

function generateQuestionCode(
  subjectPrefix: string,
  chapterName: string,
  bloomLevel: string,
  index: number
): string {
  let sub = (subjectPrefix || "QUIZ").trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!sub) sub = "QUIZ";

  let chNo = "CH00";
  const chMatch = chapterName.match(/(?:Chương|Chuong|Chapter)\s*(\d+)/i);
  if (chMatch) {
    chNo = `CH${chMatch[1].padStart(2, "0")}`;
  } else {
    const anyNum = chapterName.match(/\d+/);
    if (anyNum) {
      chNo = `CH${anyNum[0].padStart(2, "0")}`;
    }
  }

  const bloomMap: Record<string, string> = {
    "Nhận biết": "NB",
    "Thông hiểu": "TH",
    "Vận dụng": "VD",
    "Vận dụng cao": "VC",
  };
  const bl = bloomMap[bloomLevel] || "GEN";
  const idxStr = String(index).padStart(3, "0");

  return `${sub}_${chNo}_${bl}_${idxStr}`;
}

function exportToStandardBankCsv(items: import("../services/api").QuizItem[], lessonContent: string): string {
  const header = [
    "QuestionCode",
    "Chapter",
    "Topic",
    "BloomLevel",
    "Difficulty",
    "Question",
    "OptionA",
    "OptionB",
    "OptionC",
    "OptionD",
    "CorrectAnswer",
    "Explanation"
  ];
  
  const bloomMap: Record<string, string> = {
    knowledge: "Nhận biết",
    comprehension: "Thông hiểu",
    application: "Vận dụng",
    analysis: "Vận dụng cao"
  };

  const subjectPrefix = inferSubjectPrefix(lessonContent);

  const rows = items.map((item, idx) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    while (opts.length < 4) opts.push("");
    
    const bloomLevel = bloomMap[item.type] || "Nhận biết";
    const chapterName = item.chapter || "Chương chung";
    const topicName = item.topic || "Chung";
    const difficultyName = item.difficulty || "Dễ";

    const qCode = generateQuestionCode(subjectPrefix, chapterName, bloomLevel, idx + 1);

    return [
      `"${qCode}"`,
      `"${chapterName.replace(/"/g, "\"\"")}"`,
      `"${topicName.replace(/"/g, "\"\"")}"`,
      `"${bloomLevel.replace(/"/g, "\"\"")}"`,
      `"${difficultyName.replace(/"/g, "\"\"")}"`,
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      `"${item.correct_answer.toUpperCase()}"`,
      `"${item.explanation.replace(/"/g, "\"\"")}"`,
    ].join(",");
  });

  return [header.join(","), ...rows].join("\n");
}

/**
 * Export to Printable Text Format (.txt)
 */
function exportToPrintableTxt(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "==================================================",
    "                BÀI KIỂM TRA TRẮC NGHIỆM ĐỀ BẢN IN",
    "==================================================",
    "",
    "Họ và tên:...................................................... Lớp:...................",
    "Ngày làm bài:...../...../.........",
    "",
    "--------------------------------------------------",
    "PHẦN I: ĐỀ BÀI (Chọn đáp án đúng nhất)",
    "--------------------------------------------------",
    "",
  ];

  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: ${item.question}`);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`   ${letter}. ${text}`);
    });
    lines.push("");
  });

  lines.push("==================================================");
  lines.push("               ĐÁP ÁN VÀ HƯỚNG DẪN GIẢI");
  lines.push("==================================================");
  lines.push("");

  lines.push("BẢNG ĐÁP ÁN:");
  const answerKeyRow: string[] = [];
  items.forEach((item, idx) => {
    answerKeyRow.push(`Câu ${idx + 1}: ${item.correct_answer}`);
  });
  for (let i = 0; i < answerKeyRow.length; i += 5) {
    lines.push(answerKeyRow.slice(i, i + 5).join("   |   "));
  }
  lines.push("CHI TIẾT GIẢI THÍCH:");
  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: Đáp án đúng: ${item.correct_answer}`);
    if (item.explanations) {
      lines.push(`- Giải thích chi tiết các lựa chọn:`);
      Object.entries(item.explanations).forEach(([choice, exp]) => {
        lines.push(`  + Lựa chọn ${choice}: ${exp}`);
      });
    } else {
      lines.push(`- Giải thích: ${item.explanation}`);
    }
    if (item.restudy_hint) {
      lines.push(`- Gợi ý ôn tập: ${item.restudy_hint}`);
    }
    lines.push("");
  });

  return lines.join("\n");
}

function getNextIdNumber(existingItems: import("../services/api").QuizItem[]): number {
  let max = 0;
  existingItems.forEach((item) => {
    const match = item.id.match(/^q(\d+)$/);
    if (match) {
      const num = parseInt(match[1], 10);
      if (num > max) max = num;
    }
  });
  return max + 1;
}

function getQuestionsCountFromPrompt(prompt: string): number {
  const matched = (prompt || "").match(/(\d+)\s*(?:câu|cau|question)/i);
  if (matched) {
    const num = parseInt(matched[1], 10);
    if (num >= 1 && num <= 20) return num;
  }
  return 5; // default fallback
}

// ── QuizPage ───────────────────────────────────────────────────────────────────

export default function QuizPage() {
  const [items, setItems] = useState<QuizItem[]>([]);
  const [answers, setAnswers] = useState<UserAnswers>({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [loading, setLoading] = useState(true);
  const [progressVal, setProgressVal] = useState(0);
  const [error, setError] = useState("");
  const [projectId, setProjectId] = useState("");
  const [lessonContent, setLessonContent] = useState("");
  const [numQuestions, setNumQuestions] = useState(5);
  const [variationSeed, setVariationSeed] = useState<number | null>(null);
  const [stats, setStats] = useState<QuizStats | null>(null);
  const [savedId, setSavedId] = useState<number | null>(null);
  const [activeCard, setActiveCard] = useState<number | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const [filterErrors, setFilterErrors] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);

  // Modal settings
  const [showRegenModal, setShowRegenModal] = useState(false);
  const [regenCustom, setRegenCustom] = useState("");
  const [showQuizPromptGuide, setShowQuizPromptGuide] = useState(false);
  const initCalledRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Init ──────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (initCalledRef.current) return;
    initCalledRef.current = true;

    try {
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (!raw)
        throw new Error(
          "Không tìm thấy dữ liệu quiz. Vui lòng quay lại bài giảng.",
        );

      const state: QuizState = JSON.parse(raw);
      setProjectId(state.projectId || "");
      setLessonContent(state.lessonContent || "");
      setNumQuestions(state.numQuestions || 5);

      // If we already have items and seed in the storage, use them
      if (state.items && state.items.length > 0) {
        setItems(state.items);
        setVariationSeed(state.variationSeed ?? null);
        if (state.answers) setAnswers(state.answers);
        if (state.elapsed) setElapsed(state.elapsed);
        if (state.submitted) {
          setSubmitted(true);
          setScore(state.score || 0);
        }
        setLoading(false);
        getQuizStats(state.projectId || undefined)
          .then(setStats)
          .catch(() => {});
        return;
      }

      // Otherwise, instead of auto-generating, just enter setup mode
      setLoading(false);
      setShowRegenModal(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Lỗi tải dữ liệu quiz.");
      setLoading(false);
    }
  }, []);

  // ── Timer ─────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (loading || submitted || items.length === 0) return;
    timerRef.current = setInterval(() => setElapsed((e) => e + 1), 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [loading, submitted, items.length]);

  // Sanitize and clamp numQuestions when opening configuration modal to prevent 422 errors
  useEffect(() => {
    if (showRegenModal) {
      if (numQuestions > 20 || numQuestions < 1) {
        setNumQuestions(5);
      }
    }
  }, [showRegenModal, numQuestions]);

  // ── Handlers ──────────────────────────────────────────────────────────────

  const handleSelect = (questionId: string, letter: string) => {
    if (submitted) return;
    setAnswers((prev) => {
      const newAnswers = { ...prev, [questionId]: letter };
      // Persist to localStorage
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (raw) {
        const state = JSON.parse(raw);
        localStorage.setItem(
          QUIZ_STORAGE_KEY,
          JSON.stringify({ ...state, answers: newAnswers, elapsed }),
        );
      }
      return newAnswers;
    });
  };

  const handleSubmit = () => {
    if (items.length === 0) return;

    // Check if all answered
    if (!allAnswered) {
      const confirmed = window.confirm(
        `Bạn chưa hoàn thành tất cả câu hỏi (còn ${unanswered} câu). Bạn có chắc chắn muốn nộp bài không?`
      );
      if (!confirmed) {
        // Focus first unanswered
        const firstUnansweredIdx = items.findIndex(item => !answers[item.id]);
        if (firstUnansweredIdx !== -1) {
          const el = document.getElementById(`quiz-card-${firstUnansweredIdx}`);
          if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
        }
        return;
      }
    }

    if (timerRef.current) clearInterval(timerRef.current);
    let correct = 0;
    items.forEach((item) => {
      if (answers[item.id] === item.correct_answer) correct++;
    });
    setScore(correct);
    setSubmitted(true);
    window.scrollTo({ top: 0, behavior: "smooth" });

    // Save submitted state
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      state.submitted = true;
      state.score = correct;
      state.elapsed = elapsed;
      localStorage.setItem(QUIZ_STORAGE_KEY, JSON.stringify(state));
    }

    saveQuizAttempt({
      score: correct,
      total: items.length,
      num_questions: items.length,
      answers,
      project_id: projectId || undefined,
      variation_seed: variationSeed ?? undefined,
    })
      .then((res) => {
        setSavedId(res.id);
        getQuizStats(projectId || undefined)
          .then(setStats)
          .catch(() => {});
      })
      .catch(() => {});
  };

  const handleBack = () => {
    if (projectId) window.location.href = `/materials/${projectId}/editor`;
    else {
      window.close();
      window.location.href = "/";
    }
  };

  const handleRetry = () => {
    setAnswers({});
    setSubmitted(false);
    setScore(0);
    setSavedId(null);
    setElapsed(0);
    setFilterErrors(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleUpdateItem = (updatedItem: QuizItem) => {
    const newItems = items.map((q) => (q.id === updatedItem.id ? updatedItem : q));
    setItems(newItems);
    
    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
        }),
      );
    }
  };

  const handleDeleteItem = (questionId: string) => {
    const newItems = items.filter((q) => q.id !== questionId);
    setItems(newItems);
    
    // Remove the answer to this question if any
    const newAnswers = { ...answers };
    delete newAnswers[questionId];
    setAnswers(newAnswers);

    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
          answers: newAnswers,
        }),
      );
    }
  };

  const handleRegenerate = (n: number, bloom: string, custom: string, mode: "replace" | "append" = "replace") => {
    if (!lessonContent) return;
    const newSeed = Math.floor(Math.random() * 10000);
    const nextIdStart = getNextIdNumber(items);
    
    setLoading(true);
    setProgressVal(0);
    setError("");
    setShowRegenModal(false);

    const interval = setInterval(() => {
      setProgressVal((prev) => {
        if (prev >= 95) return prev;
        const increment = prev < 50 ? Math.floor(Math.random() * 6) + 4 : Math.floor(Math.random() * 2) + 1;
        return Math.min(prev + increment, 95);
      });
    }, 450);
    
    generateQuiz(lessonContent, n, newSeed, bloom, custom)
      .then((res) => {
        clearInterval(interval);
        setProgressVal(100);
        
        setTimeout(() => {
          const generatedQuestions = res.questions ?? [];
          
          let newItems: QuizItem[];
          let newAnswers: UserAnswers;
          if (mode === "append") {
            const mappedQuestions = generatedQuestions.map((q, idx) => ({
              ...q,
              id: `q${nextIdStart + idx}`
            }));
            newItems = [...items, ...mappedQuestions];
            newAnswers = { ...answers };
            setSubmitted(false);
            setScore(0);
            setSavedId(null);
            setFilterErrors(false);
          } else {
            newItems = generatedQuestions;
            newAnswers = {};
            setAnswers({});
            setSubmitted(false);
            setScore(0);
            setSavedId(null);
            setElapsed(0);
            setFilterErrors(false);
          }
          
          setItems(newItems);
          setNumQuestions(n);
          setVariationSeed(res.variation_seed ?? newSeed);
          setLoading(false);

          // Update localStorage with the new questions
          const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
          if (raw) {
            const state = JSON.parse(raw);
            localStorage.setItem(
              QUIZ_STORAGE_KEY,
              JSON.stringify({
                ...state,
                numQuestions: n,
                items: newItems,
                variationSeed: res.variation_seed ?? newSeed,
                answers: newAnswers,
                submitted: false,
                score: 0,
                elapsed: mode === "append" ? elapsed : 0,
              }),
            );
          }
        }, 300);
      })
      .catch((err) => {
        clearInterval(interval);
        setError(err instanceof Error ? err.message : "Lỗi tạo quiz.");
        setLoading(false);
      });
  };

  // ── Derived state ─────────────────────────────────────────────────────────

  const total = items.length;
  const answered = Object.keys(answers).length;
  const unanswered = total - answered;
  const progress = total > 0 ? (answered / total) * 100 : 0;
  const allAnswered = answered === total && total > 0;

  // Filtered items for "show errors only" mode
  const visibleItems = submitted && filterErrors
    ? items.filter((item) => answers[item.id] !== item.correct_answer)
    : items;

  // ── Loading / Error ────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="qp-page" style={{ background: "#ffffff", display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh" }}>
        <div className="qp-center" style={{ width: "100%", maxWidth: "360px", padding: 24, textAlign: "center", background: "#ffffff", borderRadius: 16, border: "1px solid #e2e8f0", boxShadow: "0 10px 30px rgba(0,0,0,0.08)" }}>
          <div className="qp-spinner" style={{ margin: "0 auto 16px", borderColor: "#f1f5f9", borderTopColor: "#4f46e5" }} />
          <p style={{ color: "#0f172a", fontSize: 16, margin: "0 0 8px 0", fontWeight: 700 }}>
            Đang tạo câu hỏi quiz... ({progressVal}%)
          </p>
          <div style={{ height: 6, width: "100%", background: "#f1f5f9", borderRadius: 3, overflow: "hidden", marginBottom: 12 }}>
            <div 
              style={{ height: "100%", background: "linear-gradient(90deg, #4f46e5, #6366f1)", width: `${progressVal}%`, borderRadius: 3, transition: "width 0.2s ease-out" }}
            />
          </div>
          <p style={{ color: "#64748b", fontSize: 12, margin: 0 }}>
            Gemini đang phân tích nội dung bài giảng và thiết kế câu hỏi trắc nghiệm
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div style={{ fontSize: 52 }}>⚠️</div>
          <div className="qp-error" style={{ maxWidth: 440 }}>
            <p style={{ margin: 0, color: "#fca5a5", fontWeight: 600 }}>{error}</p>
            <button className="qp-btn-primary" onClick={handleBack}>
              ← Quay lại
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="qp-page">
      {/* Header */}
      <header className="qp-header">
        <button className="qp-back-btn" onClick={handleBack}>
          ← Quay lại
        </button>

        <div className="qp-header-center">
          <h1 className="qp-header-title">📝 Luyện tập Quiz</h1>
          {variationSeed !== null && (
            <span className="qp-seed-badge">seed #{variationSeed}</span>
          )}
        </div>

        <div className="qp-header-right">
          <button
            className="qp-regen-btn"
            onClick={() => setShowRegenModal(true)}
            title="Tạo bộ câu hỏi mới"
          >
            🔀 Câu hỏi mới
          </button>

          {/* Export dropdown — only when questions are loaded */}
          {items.length > 0 && (
            <div style={{ position: "relative" }}>
              <button
                className="qp-regen-btn"
                style={{ background: "#0f766e", borderColor: "#0d9488", color: "#ffffff" }}
                onClick={() => setShowExportMenu((v) => !v)}
                title="Xuất câu hỏi ra file để dùng trên LMS"
              >
                ⬇ Xuất Quiz
              </button>
              {showExportMenu && (
                <div
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    right: 0,
                    background: "#1e293b",
                    border: "1px solid #334155",
                    borderRadius: 10,
                    padding: "6px",
                    zIndex: 50,
                    minWidth: 210,
                    boxShadow: "0 8px 32px #0008",
                  }}
                  onMouseLeave={() => setShowExportMenu(false)}
                >
                  <p style={{ margin: "4px 8px 8px", fontSize: 11, color: "#64748b", fontWeight: 700, letterSpacing: "0.06em" }}>
                    CHỌN ĐỊNH DẠNG
                  </p>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#164e63", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToGift(items), "quiz_moodle_gift.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📚 GIFT (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#1e3a8a", color: "#ffffff" }}

                    onClick={() => {
                      downloadTextFile(exportToAiken(items), "quiz_moodle_aiken.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📝 Aiken (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#14532d", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToCsv(items), "quiz_kahoot.csv", "text/csv;charset=utf-8");
                      setShowExportMenu(false);
                    }}
                  >
                    🎮 CSV (.csv) — Kahoot / Quizizz
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#0891b2", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToStandardBankCsv(items, lessonContent), "ngan_hang_cau_hoi.csv", "text/csv;charset=utf-8");
                      setShowExportMenu(false);
                    }}
                  >
                    🏫 Ngân hàng câu hỏi (.csv)
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", background: "#4f46e5", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToPrintableTxt(items), "de_thi_ban_in.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    🖨️ Bản in (.txt) — Thi viết/Tự học
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

      </header>

      {/* Progress bar (only before submit) */}
      {!submitted && (
        <div className="qp-progress-wrap">
          <div className="qp-progress-bar-track">
            <div
              className="qp-progress-bar-fill"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="qp-progress-label">
            {answered}/{total} câu đã trả lời
          </span>
          <span className="qp-timer">⏱ Thời gian: {formatTimer(elapsed)}</span>
        </div>
      )}

      {/* Main content */}
      <div className="qp-content">
        {/* Score panel (after submit) */}
        {submitted && (
          <ScorePanel
            score={score}
            total={total}
            elapsed={elapsed}
            savedId={savedId}
            stats={stats}
            items={items}
            userAnswers={answers}
            onRetry={handleRetry}
            onBack={handleBack}
          />
        )}

        {/* Filter toggle (after submit) */}
        {submitted && items.some((item) => answers[item.id] !== item.correct_answer) && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 8 }}>
            <button
              className={`qp-filter-toggle${filterErrors ? " active" : ""}`}
              onClick={() => setFilterErrors((p) => !p)}
            >
              {filterErrors ? "🔍 Đang lọc lỗi" : "❌ Chỉ hiện câu sai"}
            </button>
          </div>
        )}

        {/* Question cards */}
        {visibleItems.map((item, idx) => (
          <div key={item.id} id={`quiz-card-${items.indexOf(item)}`}>
            <QuizCard
              item={item}
              index={items.indexOf(item)}
              userAnswer={answers[item.id]}
              submitted={submitted}
              expanded={activeCard === idx}
              onSelect={handleSelect}
              onToggleExpand={(i) => setActiveCard(activeCard === i ? null : i)}
              onUpdateItem={handleUpdateItem}
              onDeleteItem={handleDeleteItem}
            />
          </div>
        ))}

        {submitted && filterErrors && visibleItems.length === 0 && (
          <div style={{
            textAlign: "center",
            padding: "40px 20px",
            color: "#4ade80",
            fontSize: 16,
            fontWeight: 600,
          }}>
            🎉 Tuyệt vời! Bạn không có câu nào sai.
          </div>
        )}
      </div>

      {/* Submit bar */}
      {!submitted && (
        <div className="qp-submit-bar">
          <span className={`qp-submit-status${allAnswered ? " all-done" : ""}`}>
            {allAnswered
              ? `✓ Đã trả lời tất cả ${total} câu`
              : `⚠ Còn ${unanswered} câu chưa trả lời`}
          </span>
          <button
            className={`qp-submit-btn${allAnswered ? " all-answered" : ""}`}
            onClick={handleSubmit}
            disabled={answered === 0}
          >
            Nộp bài →
          </button>
        </div>
      )}
      {/* Regen Modal */}
      {showRegenModal && (
        <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <div style={{ background: "#fff", padding: "24px", borderRadius: "12px", width: "100%", maxWidth: "480px", boxShadow: "0 20px 40px rgba(0,0,0,0.2)" }}>
            <h2 style={{ margin: "0 0 16px 0", fontSize: 20 }}>{items.length === 0 ? "Cấu hình Quiz" : "Tạo Quiz mới"}</h2>
            
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: "block", marginBottom: 8, fontSize: 14, fontWeight: 600 }}>Nhập yêu cầu tạo câu hỏi (Prompt)</label>
              <textarea 
                spellCheck={false}
                value={regenCustom} 
                onChange={e => {
                  setRegenCustom(e.target.value);
                  e.target.style.height = "auto";
                  e.target.style.height = `${e.target.scrollHeight}px`;
                }}
                placeholder="Nhập yêu cầu chi tiết để tạo câu hỏi hiệu quả"
                style={{ width: "100%", padding: "10px 12px", borderRadius: "8px", border: "1px solid #cbd5e1", minHeight: "42px", height: "auto", resize: "none", fontSize: 13, lineHeight: "1.5" }}
              />
            </div>

            <div style={{ fontSize: "12px", color: "#475569", background: "#f8fafc", padding: "12px", borderRadius: "8px", marginBottom: 20, border: "1px solid #e2e8f0", lineHeight: "1.6" }}>
              <div 
                onClick={() => setShowQuizPromptGuide(!showQuizPromptGuide)}
                style={{ 
                  color: "#0f172a", 
                  fontWeight: 700, 
                  cursor: "pointer", 
                  display: "flex", 
                  alignItems: "center", 
                  justifyContent: "space-between",
                  userSelect: "none"
                }}
              >
                <span>💡 Cách prompt đạt hiệu quả cao nhất</span>
                <span style={{ fontSize: "10px", color: "#64748b" }}>{showQuizPromptGuide ? "▼" : "▶"}</span>
              </div>
              
              {showQuizPromptGuide && (
                <div style={{ marginTop: 8 }} className="animate-in fade-in duration-200">
                  <ul style={{ margin: "0 0 8px 0", paddingLeft: "16px", display: "flex", flexDirection: "column", gap: "2px" }}>
                    <li>Nêu rõ số lượng cụ thể (VD: <em>"tạo 3 câu..."</em>, <em>"5 câu..."</em>).</li>
                    <li>Nêu rõ Chương/Mục kiểm tra (VD: <em>"về Chương 1"</em>, <em>"Mục 2.1"</em>).</li>
                    <li>Nêu rõ mức độ Bloom mong muốn (<em>Nhận biết</em>, <em>Thông hiểu</em>, <em>Áp dụng</em>, <em>Phân tích</em>).</li>
                  </ul>
                  <div style={{ borderTop: "1px solid #e2e8f0", paddingTop: "6px", fontSize: "11px", color: "#64748b" }}>
                    <strong>Ví dụ đầy đủ:</strong> <em>"Tạo 5 câu hỏi nâng cao mức độ Nhận biết và Thông hiểu về các khái niệm cốt lõi trong Mục 1.1 Công nghệ phần mềm."</em>
                  </div>
                </div>
              )}
            </div>
            
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {items.length === 0 ? (
                <div style={{ display: "flex", gap: 10 }}>
                  <button 
                    onClick={() => { setShowRegenModal(false); handleBack(); }}
                    style={{ flex: 1, padding: "10px 16px", borderRadius: "8px", border: "1px solid #cbd5e1", background: "#fff", cursor: "pointer", fontWeight: 600, color: "#475569", fontSize: "13px", textAlign: "center" }}
                  >
                    Quay lại
                  </button>
                  <button 
                    onClick={() => {
                      const n = getQuestionsCountFromPrompt(regenCustom);
                      handleRegenerate(n, "mix", regenCustom, "replace");
                    }}
                    style={{ 
                      flex: 1, 
                      padding: "10px 16px", 
                      borderRadius: "8px", 
                      border: "none", 
                      background: "#4f46e5", 
                      cursor: "pointer", 
                      fontWeight: 600, 
                      color: "#fff", 
                      fontSize: "13px", 
                      textAlign: "center",
                      opacity: !regenCustom.trim() ? 0.6 : 1,
                      pointerEvents: !regenCustom.trim() ? "none" : "auto"
                    }}
                    disabled={!regenCustom.trim()}
                  >
                    ✨ Bắt đầu tạo Quiz
                  </button>
                </div>
              ) : (
                <>
                  <div style={{ display: "flex", gap: 10 }}>
                    <button 
                      onClick={() => {
                        const n = getQuestionsCountFromPrompt(regenCustom);
                        handleRegenerate(n, "mix", regenCustom, "replace");
                      }}
                      style={{ 
                        flex: 1,
                        padding: "10px 12px", 
                        borderRadius: "8px", 
                        border: "none", 
                        background: "#ef4444", 
                        cursor: "pointer", 
                        fontWeight: 600, 
                        color: "#fff",
                        fontSize: "13px",
                        textAlign: "center",
                        opacity: !regenCustom.trim() ? 0.6 : 1,
                        pointerEvents: !regenCustom.trim() ? "none" : "auto"
                      }}
                      title="Xoá tất cả câu hỏi hiện tại và tạo bộ mới"
                      disabled={!regenCustom.trim()}
                    >
                      Tạo mới (Thay thế)
                    </button>
                    <button 
                      onClick={() => {
                        const n = getQuestionsCountFromPrompt(regenCustom);
                        handleRegenerate(n, "mix", regenCustom, "append");
                      }}
                      style={{ 
                        flex: 1,
                        padding: "10px 12px", 
                        borderRadius: "8px", 
                        border: "none", 
                        background: "#10b981", 
                        cursor: "pointer", 
                        fontWeight: 600, 
                        color: "#fff",
                        fontSize: "13px",
                        textAlign: "center",
                        opacity: !regenCustom.trim() ? 0.6 : 1,
                        pointerEvents: !regenCustom.trim() ? "none" : "auto"
                      }}
                      title="Giữ nguyên các câu hỏi hiện tại, chỉ tạo thêm câu hỏi mới gộp vào"
                      disabled={!regenCustom.trim()}
                    >
                      Tạo thêm & Gộp vào ({items.length})
                    </button>
                  </div>
                  <button 
                    onClick={() => setShowRegenModal(false)}
                    style={{ 
                      width: "100%", 
                      padding: "10px 16px", 
                      borderRadius: "8px", 
                      border: "1px solid #cbd5e1", 
                      background: "#fff", 
                      cursor: "pointer", 
                      fontWeight: 600, 
                      color: "#475569",
                      fontSize: "13px",
                      textAlign: "center"
                    }}
                  >
                    Hủy
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
