import { useEffect, useRef, useState } from "react";
import {
  generateQuiz,
  getQuizStats,
  saveQuizAttempt,
  analyzeQuizContent,
  type QuizItem,
  type QuizStats,
} from "../services/api";
import { QuizCard } from "../components/QuizCard";
import { ScorePanel } from "../components/ScorePanel";
import "./QuizPage.css";

// ── Constants ──────────────────────────────────────────────────────────────────

const QUIZ_STORAGE_KEY = "rag.quiz.pending";

// ── Types ──────────────────────────────────────────────────────────────────────

interface UserAnswers {
  [questionId: string]: string;
}

interface QuizState {
  items: QuizItem[];
  projectId: string;
  lessonContent: string;
  numQuestions: number;
  variationSeed?: number | null;
  answers?: UserAnswers;
  elapsed?: number;
  submitted?: boolean;
  score?: number;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function formatTimer(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${String(m).padStart(2, "00")}:${String(s).padStart(2, "00")}`;
}

// ── Export helpers ────────────────────────────────────────────────────────────

/** Download a text blob with the given filename */
function downloadTextFile(content: string, filename: string, mime = "text/plain;charset=utf-8") {
  const blob = new Blob(["\uFEFF" + content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 200);
}

/**
 * Export to Moodle GIFT format (.txt)
 * Spec: https://docs.moodle.org/en/GIFT_format
 * Supports MCQ only (4 options A–D)
 */
function exportToGift(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "// GIFT format — Generated by RAG Teaching Material",
    "// Import: Moodle > Question Bank > Import > GIFT format",
    "",
  ];
  items.forEach((item, idx) => {
    // Escape special GIFT chars: { } = # ~
    const esc = (s: string) => s.replace(/[{}=#~]/g, "\\$&");
    lines.push(`// Question ${idx + 1}`);
    lines.push(`::Q${idx + 1}:: ${esc(item.question)} {`);
    item.options.forEach((opt) => {
      // opt format: "A. text" or "A) text"
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      const isCorrect = letter === item.correct_answer.toUpperCase();
      // GIFT: = correct, ~ wrong
      lines.push(`  ${isCorrect ? "=" : "~"} ${esc(text)}`);
    });
    lines.push(`}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Moodle Aiken format (.txt)
 * Spec: https://docs.moodle.org/en/Aiken_format
 * Very simple and human-readable format for multiple choice.
 */
function exportToAiken(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [];
  items.forEach((item) => {
    lines.push(item.question);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`${letter}) ${text}`);
    });
    lines.push(`ANSWER: ${item.correct_answer.toUpperCase()}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Kahoot-compatible CSV (.csv)
 * Columns: Question, Answer 1, Answer 2, Answer 3, Answer 4, Time limit, Correct answer
 * Correct answer = 1-indexed position of correct option
 */
function exportToCsv(items: import("../services/api").QuizItem[]): string {
  const header = ["Question", "Answer 1", "Answer 2", "Answer 3", "Answer 4", "Time limit (sec)", "Correct answer"];
  const rows = items.map((item) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    // Pad to 4 answers if needed
    while (opts.length < 4) opts.push("");
    const correctIdx = ["A", "B", "C", "D"].indexOf(item.correct_answer.toUpperCase()) + 1;
    return [
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      "60",
      String(correctIdx),
    ].join(",");
  });
  return [header.join(","), ...rows].join("\n");
}

/**
 * Export to Printable Text Format (.txt)
 */
function exportToPrintableTxt(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "==================================================",
    "                BÀI KIỂM TRA TRẮC NGHIỆM ĐỀ BẢN IN",
    "==================================================",
    "",
    "Họ và tên:...................................................... Lớp:...................",
    "Ngày làm bài:...../...../.........",
    "",
    "--------------------------------------------------",
    "PHẦN I: ĐỀ BÀI (Chọn đáp án đúng nhất)",
    "--------------------------------------------------",
    "",
  ];

  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: ${item.question}`);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`   ${letter}. ${text}`);
    });
    lines.push("");
  });

  lines.push("==================================================");
  lines.push("               ĐÁP ÁN VÀ HƯỚNG DẪN GIẢI");
  lines.push("==================================================");
  lines.push("");

  lines.push("BẢNG ĐÁP ÁN:");
  const answerKeyRow: string[] = [];
  items.forEach((item, idx) => {
    answerKeyRow.push(`Câu ${idx + 1}: ${item.correct_answer}`);
  });
  for (let i = 0; i < answerKeyRow.length; i += 5) {
    lines.push(answerKeyRow.slice(i, i + 5).join("   |   "));
  }
  lines.push("");
  lines.push("CHI TIẾT GIẢI THÍCH:");
  items.forEach((item, idx) => {
    lines.push(`Câu ${idx + 1}: Đáp án đúng: ${item.correct_answer}`);
    lines.push(`- Giải thích: ${item.explanation}`);
    if (item.restudy_hint) {
      lines.push(`- Gợi ý ôn tập: ${item.restudy_hint}`);
    }
    lines.push("");
  });

  return lines.join("\n");
}

function getNextIdNumber(existingItems: import("../services/api").QuizItem[]): number {
  let max = 0;
  existingItems.forEach((item) => {
    const match = item.id.match(/^q(\d+)$/);
    if (match) {
      const num = parseInt(match[1], 10);
      if (num > max) max = num;
    }
  });
  return max + 1;
}

// ── QuizPage ───────────────────────────────────────────────────────────────────

export default function QuizPage() {
  const [items, setItems] = useState<QuizItem[]>([]);
  const [answers, setAnswers] = useState<UserAnswers>({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [projectId, setProjectId] = useState("");
  const [lessonContent, setLessonContent] = useState("");
  const [numQuestions, setNumQuestions] = useState(5);
  const [variationSeed, setVariationSeed] = useState<number | null>(null);
  const [stats, setStats] = useState<QuizStats | null>(null);
  const [savedId, setSavedId] = useState<number | null>(null);
  const [activeCard, setActiveCard] = useState<number | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const [filterErrors, setFilterErrors] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);

  // Modal settings
  const [showRegenModal, setShowRegenModal] = useState(false);
  const [regenBloom, setRegenBloom] = useState("mix");
  const [regenCustom, setRegenCustom] = useState("");
  const [analyzing, setAnalyzing] = useState(false);
  const [aiSuggestedNum, setAiSuggestedNum] = useState<number | null>(null);
  const [aiAnalysisText, setAiAnalysisText] = useState("");
  const initCalledRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Init ──────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (initCalledRef.current) return;
    initCalledRef.current = true;

    try {
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (!raw)
        throw new Error(
          "Không tìm thấy dữ liệu quiz. Vui lòng quay lại bài giảng.",
        );

      const state: QuizState = JSON.parse(raw);
      setProjectId(state.projectId || "");
      setLessonContent(state.lessonContent || "");
      setNumQuestions(state.numQuestions || 5);

      // If we already have items and seed in the storage, use them
      if (state.items && state.items.length > 0) {
        setItems(state.items);
        setVariationSeed(state.variationSeed ?? null);
        if (state.answers) setAnswers(state.answers);
        if (state.elapsed) setElapsed(state.elapsed);
        if (state.submitted) {
          setSubmitted(true);
          setScore(state.score || 0);
        }
        setLoading(false);
        getQuizStats(state.projectId || undefined)
          .then(setStats)
          .catch(() => {});
        return;
      }

      // Otherwise, instead of auto-generating, just enter setup mode
      setLoading(false);
      setShowRegenModal(true);
      setAnalyzing(true);
      analyzeQuizContent(state.lessonContent)
        .then((res) => {
          setAiSuggestedNum(res.suggested_count);
          setNumQuestions(res.suggested_count);
          setAiAnalysisText(`Độ khó: ${res.complexity}. ${res.reasoning}`);
        })
        .catch(() => {
          setAiAnalysisText("Lỗi phân tích nội dung.");
        })
        .finally(() => setAnalyzing(false));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Lỗi tải dữ liệu quiz.");
      setLoading(false);
    }
  }, []);

  // ── Timer ─────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (loading || submitted || items.length === 0) return;
    timerRef.current = setInterval(() => setElapsed((e) => e + 1), 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [loading, submitted, items.length]);

  // ── Handlers ──────────────────────────────────────────────────────────────

  const handleSelect = (questionId: string, letter: string) => {
    if (submitted) return;
    setAnswers((prev) => {
      const newAnswers = { ...prev, [questionId]: letter };
      // Persist to localStorage
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (raw) {
        const state = JSON.parse(raw);
        localStorage.setItem(
          QUIZ_STORAGE_KEY,
          JSON.stringify({ ...state, answers: newAnswers, elapsed }),
        );
      }
      return newAnswers;
    });
  };

  const handleSubmit = () => {
    if (items.length === 0) return;

    // Check if all answered
    if (!allAnswered) {
      const confirmed = window.confirm(
        `Bạn chưa hoàn thành tất cả câu hỏi (còn ${unanswered} câu). Bạn có chắc chắn muốn nộp bài không?`
      );
      if (!confirmed) {
        // Focus first unanswered
        const firstUnansweredIdx = items.findIndex(item => !answers[item.id]);
        if (firstUnansweredIdx !== -1) {
          const el = document.getElementById(`quiz-card-${firstUnansweredIdx}`);
          if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
        }
        return;
      }
    }

    if (timerRef.current) clearInterval(timerRef.current);
    let correct = 0;
    items.forEach((item) => {
      if (answers[item.id] === item.correct_answer) correct++;
    });
    setScore(correct);
    setSubmitted(true);
    window.scrollTo({ top: 0, behavior: "smooth" });

    // Save submitted state
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      state.submitted = true;
      state.score = correct;
      state.elapsed = elapsed;
      localStorage.setItem(QUIZ_STORAGE_KEY, JSON.stringify(state));
    }

    saveQuizAttempt({
      score: correct,
      total: items.length,
      num_questions: items.length,
      answers,
      project_id: projectId || undefined,
      variation_seed: variationSeed ?? undefined,
    })
      .then((res) => {
        setSavedId(res.id);
        getQuizStats(projectId || undefined)
          .then(setStats)
          .catch(() => {});
      })
      .catch(() => {});
  };

  const handleBack = () => {
    if (projectId) window.location.href = `/materials/${projectId}/editor`;
    else {
      window.close();
      window.location.href = "/";
    }
  };

  const handleRetry = () => {
    setAnswers({});
    setSubmitted(false);
    setScore(0);
    setSavedId(null);
    setElapsed(0);
    setFilterErrors(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleUpdateItem = (updatedItem: QuizItem) => {
    const newItems = items.map((q) => (q.id === updatedItem.id ? updatedItem : q));
    setItems(newItems);
    
    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
        }),
      );
    }
  };

  const handleDeleteItem = (questionId: string) => {
    const newItems = items.filter((q) => q.id !== questionId);
    setItems(newItems);
    
    // Remove the answer to this question if any
    const newAnswers = { ...answers };
    delete newAnswers[questionId];
    setAnswers(newAnswers);

    // Save to localStorage
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      localStorage.setItem(
        QUIZ_STORAGE_KEY,
        JSON.stringify({
          ...state,
          items: newItems,
          answers: newAnswers,
        }),
      );
    }
  };

  const handleRegenerate = (n: number, bloom: string, custom: string, mode: "replace" | "append" = "replace") => {
    if (!lessonContent) return;
    const newSeed = Math.floor(Math.random() * 10000);
    const nextIdStart = getNextIdNumber(items);
    
    setLoading(true);
    setError("");
    setShowRegenModal(false);
    
    generateQuiz(lessonContent, n, newSeed, bloom, custom)
      .then((res) => {
        const generatedQuestions = res.questions ?? [];
        
        let newItems: QuizItem[];
        let newAnswers: UserAnswers;
        if (mode === "append") {
          const mappedQuestions = generatedQuestions.map((q, idx) => ({
            ...q,
            id: `q${nextIdStart + idx}`
          }));
          newItems = [...items, ...mappedQuestions];
          newAnswers = { ...answers };
          setSubmitted(false);
          setScore(0);
          setSavedId(null);
          setFilterErrors(false);
        } else {
          newItems = generatedQuestions;
          newAnswers = {};
          setAnswers({});
          setSubmitted(false);
          setScore(0);
          setSavedId(null);
          setElapsed(0);
          setFilterErrors(false);
        }
        
        setItems(newItems);
        setNumQuestions(n);
        setVariationSeed(res.variation_seed ?? newSeed);
        setLoading(false);

        // Update localStorage with the new questions
        const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
        if (raw) {
          const state = JSON.parse(raw);
          localStorage.setItem(
            QUIZ_STORAGE_KEY,
            JSON.stringify({
              ...state,
              numQuestions: n,
              items: newItems,
              variationSeed: res.variation_seed ?? newSeed,
              answers: newAnswers,
              submitted: false,
              score: 0,
              elapsed: mode === "append" ? elapsed : 0,
            }),
          );
        }
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : "Lỗi tạo quiz.");
        setLoading(false);
      });
  };

  // ── Derived state ─────────────────────────────────────────────────────────

  const total = items.length;
  const answered = Object.keys(answers).length;
  const unanswered = total - answered;
  const progress = total > 0 ? (answered / total) * 100 : 0;
  const allAnswered = answered === total && total > 0;

  // Filtered items for "show errors only" mode
  const visibleItems = submitted && filterErrors
    ? items.filter((item) => answers[item.id] !== item.correct_answer)
    : items;

  // ── Loading / Error ────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div className="qp-spinner" />
          <p style={{ color: "#818cf8", fontSize: 15, margin: 0, fontWeight: 500 }}>
            Đang tạo câu hỏi quiz...
          </p>
          <p style={{ color: "#475569", fontSize: 12, margin: 0 }}>
            Gemini đang phân tích nội dung bài giảng
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div style={{ fontSize: 52 }}>⚠️</div>
          <div className="qp-error" style={{ maxWidth: 440 }}>
            <p style={{ margin: 0, color: "#fca5a5", fontWeight: 600 }}>{error}</p>
            <button className="qp-btn-primary" onClick={handleBack}>
              ← Quay lại
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="qp-page">
      {/* Header */}
      <header className="qp-header">
        <button className="qp-back-btn" onClick={handleBack}>
          ← Quay lại
        </button>

        <div className="qp-header-center">
          <h1 className="qp-header-title">📝 Luyện tập Quiz</h1>
          {variationSeed !== null && (
            <span className="qp-seed-badge">seed #{variationSeed}</span>
          )}
        </div>

        <div className="qp-header-right">
          <button
            className="qp-regen-btn"
            onClick={() => setShowRegenModal(true)}
            title="Tạo bộ câu hỏi mới"
          >
            🔀 Câu hỏi mới
          </button>

          {/* Export dropdown — only when questions are loaded */}
          {items.length > 0 && (
            <div style={{ position: "relative" }}>
              <button
                className="qp-regen-btn"
                style={{ background: "#0f766e", borderColor: "#0d9488", color: "#ffffff" }}
                onClick={() => setShowExportMenu((v) => !v)}
                title="Xuất câu hỏi ra file để dùng trên LMS"
              >
                ⬇ Xuất Quiz
              </button>
              {showExportMenu && (
                <div
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    right: 0,
                    background: "#1e293b",
                    border: "1px solid #334155",
                    borderRadius: 10,
                    padding: "6px",
                    zIndex: 50,
                    minWidth: 210,
                    boxShadow: "0 8px 32px #0008",
                  }}
                  onMouseLeave={() => setShowExportMenu(false)}
                >
                  <p style={{ margin: "4px 8px 8px", fontSize: 11, color: "#64748b", fontWeight: 700, letterSpacing: "0.06em" }}>
                    CHỌN ĐỊNH DẠNG
                  </p>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#164e63", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToGift(items), "quiz_moodle_gift.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📚 GIFT (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#1e3a8a", color: "#ffffff" }}

                    onClick={() => {
                      downloadTextFile(exportToAiken(items), "quiz_moodle_aiken.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📝 Aiken (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#14532d", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToCsv(items), "quiz_kahoot.csv", "text/csv;charset=utf-8");
                      setShowExportMenu(false);
                    }}
                  >
                    🎮 CSV (.csv) — Kahoot / Quizizz
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", background: "#4f46e5", color: "#ffffff" }}
                    onClick={() => {
                      downloadTextFile(exportToPrintableTxt(items), "de_thi_ban_in.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    🖨️ Bản in (.txt) — Thi viết/Tự học
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

      </header>

      {/* Progress bar (only before submit) */}
      {!submitted && (
        <div className="qp-progress-wrap">
          <div className="qp-progress-bar-track">
            <div
              className="qp-progress-bar-fill"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="qp-progress-label">
            {answered}/{total} câu đã trả lời
          </span>
          <span className="qp-timer">⏱ Thời gian: {formatTimer(elapsed)}</span>
        </div>
      )}

      {/* Main content */}
      <div className="qp-content">
        {/* Score panel (after submit) */}
        {submitted && (
          <ScorePanel
            score={score}
            total={total}
            elapsed={elapsed}
            savedId={savedId}
            stats={stats}
            items={items}
            userAnswers={answers}
            onRetry={handleRetry}
            onBack={handleBack}
          />
        )}

        {/* Filter toggle (after submit) */}
        {submitted && items.some((item) => answers[item.id] !== item.correct_answer) && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 8 }}>
            <button
              className={`qp-filter-toggle${filterErrors ? " active" : ""}`}
              onClick={() => setFilterErrors((p) => !p)}
            >
              {filterErrors ? "🔍 Đang lọc lỗi" : "❌ Chỉ hiện câu sai"}
            </button>
          </div>
        )}

        {/* Question cards */}
        {visibleItems.map((item, idx) => (
          <div key={item.id} id={`quiz-card-${items.indexOf(item)}`}>
            <QuizCard
              item={item}
              index={items.indexOf(item)}
              userAnswer={answers[item.id]}
              submitted={submitted}
              expanded={activeCard === idx}
              onSelect={handleSelect}
              onToggleExpand={(i) => setActiveCard(activeCard === i ? null : i)}
              onUpdateItem={handleUpdateItem}
              onDeleteItem={handleDeleteItem}
            />
          </div>
        ))}

        {submitted && filterErrors && visibleItems.length === 0 && (
          <div style={{
            textAlign: "center",
            padding: "40px 20px",
            color: "#4ade80",
            fontSize: 16,
            fontWeight: 600,
          }}>
            🎉 Tuyệt vời! Bạn không có câu nào sai.
          </div>
        )}
      </div>

      {/* Submit bar */}
      {!submitted && (
        <div className="qp-submit-bar">
          <span className={`qp-submit-status${allAnswered ? " all-done" : ""}`}>
            {allAnswered
              ? `✓ Đã trả lời tất cả ${total} câu`
              : `⚠ Còn ${unanswered} câu chưa trả lời`}
          </span>
          <button
            className={`qp-submit-btn${allAnswered ? " all-answered" : ""}`}
            onClick={handleSubmit}
            disabled={answered === 0}
          >
            Nộp bài →
          </button>
        </div>
      )}
      {/* Regen Modal */}
      {showRegenModal && (
        <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <div style={{ background: "#fff", padding: "24px", borderRadius: "12px", width: "100%", maxWidth: "400px", boxShadow: "0 20px 40px rgba(0,0,0,0.2)" }}>
            <h2 style={{ margin: "0 0 16px 0", fontSize: 20 }}>{items.length === 0 ? "Cấu hình Quiz" : "Tạo Quiz mới"}</h2>
            
            {analyzing ? (
              <div style={{ marginBottom: 16, padding: "12px", background: "#f8fafc", borderRadius: "8px", display: "flex", gap: "8px", alignItems: "center" }}>
                <div className="qp-spinner" style={{ width: 16, height: 16, borderWidth: 2 }} />
                <span style={{ fontSize: 13, color: "#64748b" }}>AI đang phân tích bài giảng...</span>
              </div>
            ) : aiAnalysisText ? (
              <div style={{ marginBottom: 16, padding: "12px", background: "#f0fdf4", borderRadius: "8px", border: "1px solid #bbf7d0" }}>
                <span style={{ fontSize: 13, color: "#166534", lineHeight: 1.5 }}>
                  <strong style={{ color: "#15803d" }}>🤖 Phân tích:</strong> {aiAnalysisText}
                </span>
              </div>
            ) : null}

            <div style={{ marginBottom: 16 }}>
              <label style={{ display: "block", marginBottom: 8, fontSize: 14, fontWeight: 600 }}>Số lượng câu hỏi (tối đa 20)</label>
              <select 
                value={numQuestions} 
                onChange={e => setNumQuestions(Number(e.target.value))}
                style={{ width: "100%", padding: "8px 12px", borderRadius: "6px", border: "1px solid #cbd5e1" }}
                disabled={analyzing}
              >
                {Array.from(new Set([3, 5, 7, 10, 15, 20, aiSuggestedNum].filter((n): n is number => n !== null))).sort((a, b) => a - b).map(n => (
                  <option key={n} value={n}>
                    {n} câu {n === aiSuggestedNum ? " (🤖 AI đề xuất)" : ""}
                  </option>
                ))}
              </select>
            </div>
            
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: "block", marginBottom: 8, fontSize: 14, fontWeight: 600 }}>Mức độ Bloom</label>
              <select 
                value={regenBloom} 
                onChange={e => setRegenBloom(e.target.value)}
                style={{ width: "100%", padding: "8px 12px", borderRadius: "6px", border: "1px solid #cbd5e1" }}
              >
                <option value="mix">Trộn lẫn (Khuyên dùng)</option>
                <option value="knowledge">Chỉ Nhận biết</option>
                <option value="comprehension">Chỉ Hiểu</option>
                <option value="application">Chỉ Áp dụng</option>
                <option value="analysis">Chỉ Phân tích</option>
              </select>
            </div>
            
            <div style={{ marginBottom: 24 }}>
              <label style={{ display: "block", marginBottom: 8, fontSize: 14, fontWeight: 600 }}>Yêu cầu thêm (tuỳ chọn)</label>
              <textarea 
                value={regenCustom} 
                onChange={e => setRegenCustom(e.target.value)}
                placeholder="VD: Tập trung vào chương 2, độ khó cao..."
                style={{ width: "100%", padding: "8px 12px", borderRadius: "6px", border: "1px solid #cbd5e1", minHeight: "80px", resize: "none" }}
              />
            </div>
            
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {items.length === 0 ? (
                <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
                  <button 
                    onClick={() => { setShowRegenModal(false); handleBack(); }}
                    style={{ padding: "8px 16px", borderRadius: "6px", border: "1px solid #cbd5e1", background: "#fff", cursor: "pointer", fontWeight: 600, color: "#475569" }}
                  >
                    Quay lại
                  </button>
                  <button 
                    onClick={() => handleRegenerate(numQuestions, regenBloom, regenCustom, "replace")}
                    style={{ padding: "8px 16px", borderRadius: "6px", border: "none", background: "#4f46e5", cursor: "pointer", fontWeight: 600, color: "#fff" }}
                    disabled={analyzing}
                  >
                    ✨ Bắt đầu tạo Quiz
                  </button>
                </div>
              ) : (
                <>
                  <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
                    <button 
                      onClick={() => setShowRegenModal(false)}
                      style={{ padding: "8px 16px", borderRadius: "6px", border: "1px solid #cbd5e1", background: "#fff", cursor: "pointer", fontWeight: 600, color: "#475569" }}
                    >
                      Huỷ
                    </button>
                    <button 
                      onClick={() => handleRegenerate(numQuestions, regenBloom, regenCustom, "replace")}
                      style={{ padding: "8px 16px", borderRadius: "6px", border: "none", background: "#ef4444", cursor: "pointer", fontWeight: 600, color: "#fff" }}
                      title="Xoá tất cả câu hỏi hiện tại và tạo bộ mới"
                      disabled={analyzing}
                    >
                      Tạo mới (Thay thế)
                    </button>
                  </div>
                  <button 
                    onClick={() => handleRegenerate(numQuestions, regenBloom, regenCustom, "append")}
                    style={{ padding: "8px 16px", borderRadius: "6px", border: "none", background: "#10b981", cursor: "pointer", fontWeight: 600, color: "#fff", width: "100%" }}
                    title="Giữ nguyên các câu hỏi hiện tại, chỉ tạo thêm câu hỏi mới gộp vào"
                    disabled={analyzing}
                  >
                    ➕ Tạo thêm & Gộp vào ({items.length} câu hiện có)
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
