import { useEffect, useRef, useState } from "react";
import {
  generateQuiz,
  getQuizStats,
  saveQuizAttempt,
  type QuizItem,
  type QuizStats,
} from "../services/api";
import { QuizCard } from "../components/QuizCard";
import { ScorePanel } from "../components/ScorePanel";
import "./QuizPage.css";

// ── Constants ──────────────────────────────────────────────────────────────────

const QUIZ_STORAGE_KEY = "rag.quiz.pending";

// ── Types ──────────────────────────────────────────────────────────────────────

interface UserAnswers {
  [questionId: string]: string;
}

interface QuizState {
  items: QuizItem[];
  projectId: string;
  lessonContent: string;
  numQuestions: number;
  variationSeed?: number | null;
  answers?: UserAnswers;
  elapsed?: number;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function formatTimer(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${String(m).padStart(2, "00")}:${String(s).padStart(2, "00")}`;
}

// ── Export helpers ────────────────────────────────────────────────────────────

/** Download a text blob with the given filename */
function downloadTextFile(content: string, filename: string, mime = "text/plain;charset=utf-8") {
  const blob = new Blob(["\uFEFF" + content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 200);
}

/**
 * Export to Moodle GIFT format (.txt)
 * Spec: https://docs.moodle.org/en/GIFT_format
 * Supports MCQ only (4 options A–D)
 */
function exportToGift(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [
    "// GIFT format — Generated by RAG Teaching Material",
    "// Import: Moodle > Question Bank > Import > GIFT format",
    "",
  ];
  items.forEach((item, idx) => {
    // Escape special GIFT chars: { } = # ~
    const esc = (s: string) => s.replace(/[{}=#~]/g, "\\$&");
    lines.push(`// Question ${idx + 1}`);
    lines.push(`::Q${idx + 1}:: ${esc(item.question)} {`);
    item.options.forEach((opt) => {
      // opt format: "A. text" or "A) text"
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      const isCorrect = letter === item.correct_answer.toUpperCase();
      // GIFT: = correct, ~ wrong
      lines.push(`  ${isCorrect ? "=" : "~"} ${esc(text)}`);
    });
    lines.push(`}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Moodle Aiken format (.txt)
 * Spec: https://docs.moodle.org/en/Aiken_format
 * Very simple and human-readable format for multiple choice.
 */
function exportToAiken(items: import("../services/api").QuizItem[]): string {
  const lines: string[] = [];
  items.forEach((item) => {
    lines.push(item.question);
    item.options.forEach((opt) => {
      const letter = opt.match(/^([A-D])[.)]/i)?.[1]?.toUpperCase() ?? "";
      const text = opt.replace(/^[A-D][.)\s]+/i, "").trim();
      lines.push(`${letter}) ${text}`);
    });
    lines.push(`ANSWER: ${item.correct_answer.toUpperCase()}`);
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Export to Kahoot-compatible CSV (.csv)
 * Columns: Question, Answer 1, Answer 2, Answer 3, Answer 4, Time limit, Correct answer
 * Correct answer = 1-indexed position of correct option
 */
function exportToCsv(items: import("../services/api").QuizItem[]): string {
  const header = ["Question", "Answer 1", "Answer 2", "Answer 3", "Answer 4", "Time limit (sec)", "Correct answer"];
  const rows = items.map((item) => {
    const opts = item.options.map((o) => o.replace(/^[A-D][.)\s]+/i, "").trim());
    // Pad to 4 answers if needed
    while (opts.length < 4) opts.push("");
    const correctIdx = ["A", "B", "C", "D"].indexOf(item.correct_answer.toUpperCase()) + 1;
    return [
      `"${item.question.replace(/"/g, "\"\"")}"`,
      `"${opts[0].replace(/"/g, "\"\"")}"`,
      `"${opts[1].replace(/"/g, "\"\"")}"`,
      `"${opts[2].replace(/"/g, "\"\"")}"`,
      `"${opts[3].replace(/"/g, "\"\"")}"`,
      "60",
      String(correctIdx),
    ].join(",");
  });
  return [header.join(","), ...rows].join("\n");
}

// ── QuizPage ───────────────────────────────────────────────────────────────────

export default function QuizPage() {
  const [items, setItems] = useState<QuizItem[]>([]);
  const [answers, setAnswers] = useState<UserAnswers>({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [projectId, setProjectId] = useState("");
  const [lessonContent, setLessonContent] = useState("");
  const [numQuestions, setNumQuestions] = useState(5);
  const [variationSeed, setVariationSeed] = useState<number | null>(null);
  const [stats, setStats] = useState<QuizStats | null>(null);
  const [savedId, setSavedId] = useState<number | null>(null);
  const [activeCard, setActiveCard] = useState<number | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const [filterErrors, setFilterErrors] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const initCalledRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Init ──────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (initCalledRef.current) return;
    initCalledRef.current = true;

    try {
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (!raw)
        throw new Error(
          "Không tìm thấy dữ liệu quiz. Vui lòng quay lại bài giảng.",
        );

      const state: QuizState = JSON.parse(raw);
      setProjectId(state.projectId || "");
      setLessonContent(state.lessonContent || "");
      setNumQuestions(state.numQuestions || 5);

      // If we already have items and seed in the storage, use them
      if (state.items && state.items.length > 0) {
        setItems(state.items);
        setVariationSeed(state.variationSeed ?? null);
        if (state.answers) setAnswers(state.answers);
        if (state.elapsed) setElapsed(state.elapsed);
        setLoading(false);
        getQuizStats(state.projectId || undefined)
          .then(setStats)
          .catch(() => {});
        return;
      }

      // Otherwise, generate new questions
      generateQuiz(state.lessonContent, state.numQuestions)
        .then((res) => {
          const newItems = res.questions ?? [];
          const newSeed = res.variation_seed ?? null;
          setItems(newItems);
          setVariationSeed(newSeed);
          setLoading(false);

          // Save back to localStorage to persist on reload
          const newState = {
            ...state,
            items: newItems,
            variationSeed: newSeed,
          };
          localStorage.setItem(QUIZ_STORAGE_KEY, JSON.stringify(newState));

          getQuizStats(state.projectId || undefined)
            .then(setStats)
            .catch(() => {});
        })
        .catch((err) => {
          setError(
            err instanceof Error
              ? err.message
              : "Lỗi tạo quiz. Vui lòng thử lại.",
          );
          setLoading(false);
        });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Lỗi tải dữ liệu quiz.");
      setLoading(false);
    }
  }, []);

  // ── Timer ─────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (loading || submitted || items.length === 0) return;
    timerRef.current = setInterval(() => setElapsed((e) => e + 1), 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [loading, submitted, items.length]);

  // ── Handlers ──────────────────────────────────────────────────────────────

  const handleSelect = (questionId: string, letter: string) => {
    if (submitted) return;
    setAnswers((prev) => {
      const newAnswers = { ...prev, [questionId]: letter };
      // Persist to localStorage
      const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
      if (raw) {
        const state = JSON.parse(raw);
        localStorage.setItem(
          QUIZ_STORAGE_KEY,
          JSON.stringify({ ...state, answers: newAnswers, elapsed }),
        );
      }
      return newAnswers;
    });
  };

  const handleSubmit = () => {
    if (items.length === 0) return;

    // Check if all answered
    if (!allAnswered) {
      const confirmed = window.confirm(
        `Bạn chưa hoàn thành tất cả câu hỏi (còn ${unanswered} câu). Bạn có chắc chắn muốn nộp bài không?`
      );
      if (!confirmed) {
        // Focus first unanswered
        const firstUnansweredIdx = items.findIndex(item => !answers[item.id]);
        if (firstUnansweredIdx !== -1) {
          const el = document.getElementById(`quiz-card-${firstUnansweredIdx}`);
          if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
        }
        return;
      }
    }

    if (timerRef.current) clearInterval(timerRef.current);
    let correct = 0;
    items.forEach((item) => {
      if (answers[item.id] === item.correct_answer) correct++;
    });
    setScore(correct);
    setSubmitted(true);
    window.scrollTo({ top: 0, behavior: "smooth" });

    // Clear draft on submission
    const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
    if (raw) {
      const state = JSON.parse(raw);
      delete state.answers;
      delete state.elapsed;
      localStorage.setItem(QUIZ_STORAGE_KEY, JSON.stringify(state));
    }

    saveQuizAttempt({
      score: correct,
      total: items.length,
      num_questions: items.length,
      answers,
      project_id: projectId || undefined,
      variation_seed: variationSeed ?? undefined,
    })
      .then((res) => {
        setSavedId(res.id);
        getQuizStats(projectId || undefined)
          .then(setStats)
          .catch(() => {});
      })
      .catch(() => {});
  };

  const handleBack = () => {
    if (projectId) window.location.href = `/materials/${projectId}/editor`;
    else {
      window.close();
      window.location.href = "/";
    }
  };

  const handleRetry = () => {
    setAnswers({});
    setSubmitted(false);
    setScore(0);
    setSavedId(null);
    setElapsed(0);
    setFilterErrors(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleRegenerate = () => {
    if (!lessonContent) return;
    const newSeed = Math.floor(Math.random() * 10000);
    setAnswers({});
    setSubmitted(false);
    setScore(0);
    setSavedId(null);
    setElapsed(0);
    setFilterErrors(false);
    setLoading(true);
    setError("");
    generateQuiz(lessonContent, numQuestions, newSeed)
      .then((res) => {
        const newItems = res.questions ?? [];
        setItems(newItems);
        setVariationSeed(res.variation_seed ?? newSeed);
        setLoading(false);

        // Update localStorage with the new questions
        const raw = localStorage.getItem(QUIZ_STORAGE_KEY);
        if (raw) {
          const state = JSON.parse(raw);
          localStorage.setItem(
            QUIZ_STORAGE_KEY,
            JSON.stringify({
              ...state,
              numQuestions,
              items: newItems,
              variationSeed: res.variation_seed ?? newSeed,
            }),
          );
        }
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : "Lỗi tạo quiz.");
        setLoading(false);
      });
  };

  // ── Derived state ─────────────────────────────────────────────────────────

  const total = items.length;
  const answered = Object.keys(answers).length;
  const unanswered = total - answered;
  const progress = total > 0 ? (answered / total) * 100 : 0;
  const allAnswered = answered === total && total > 0;

  // Filtered items for "show errors only" mode
  const visibleItems = submitted && filterErrors
    ? items.filter((item) => answers[item.id] !== item.correct_answer)
    : items;

  // ── Loading / Error ────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div className="qp-spinner" />
          <p style={{ color: "#818cf8", fontSize: 15, margin: 0, fontWeight: 500 }}>
            Đang tạo câu hỏi quiz...
          </p>
          <p style={{ color: "#475569", fontSize: 12, margin: 0 }}>
            Gemini đang phân tích nội dung bài giảng
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="qp-page">
        <div className="qp-center">
          <div style={{ fontSize: 52 }}>⚠️</div>
          <div className="qp-error" style={{ maxWidth: 440 }}>
            <p style={{ margin: 0, color: "#fca5a5", fontWeight: 600 }}>{error}</p>
            <button className="qp-btn-primary" onClick={handleBack}>
              ← Quay lại bài giảng
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="qp-page">
      {/* Header */}
      <header className="qp-header">
        <button className="qp-back-btn" onClick={handleBack}>
          ← Quay lại
        </button>

        <div className="qp-header-center">
          <h1 className="qp-header-title">📝 Luyện tập Quiz</h1>
          {variationSeed !== null && (
            <span className="qp-seed-badge">seed #{variationSeed}</span>
          )}
        </div>

        <div className="qp-header-right">
          {/* Num questions selector — only when not submitted */}
          {!submitted && (
            <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#64748b" }}>
              Câu:
              <select
                className="qp-num-select"
                value={numQuestions}
                onChange={(e) => setNumQuestions(+e.target.value)}
                title="Số câu hỏi khi tạo lại"
              >
                {[5, 10, 15, 20].map((n) => (
                  <option key={n} value={n}>{n}</option>
                ))}
              </select>
            </label>
          )}
          <button
            className="qp-regen-btn"
            onClick={handleRegenerate}
            title={`Tạo bộ ${numQuestions} câu hỏi mới`}
          >
            🔀 Câu hỏi mới
          </button>

          {/* Export dropdown — only when questions are loaded */}
          {items.length > 0 && (
            <div style={{ position: "relative" }}>
              <button
                className="qp-regen-btn"
                style={{ background: "#0f766e", borderColor: "#0d9488" }}
                onClick={() => setShowExportMenu((v) => !v)}
                title="Xuất câu hỏi ra file để dùng trên LMS"
              >
                ⬇ Xuất Quiz
              </button>
              {showExportMenu && (
                <div
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    right: 0,
                    background: "#1e293b",
                    border: "1px solid #334155",
                    borderRadius: 10,
                    padding: "6px",
                    zIndex: 50,
                    minWidth: 210,
                    boxShadow: "0 8px 32px #0008",
                  }}
                  onMouseLeave={() => setShowExportMenu(false)}
                >
                  <p style={{ margin: "4px 8px 8px", fontSize: 11, color: "#64748b", fontWeight: 700, letterSpacing: "0.06em" }}>
                    CHỌN ĐỊNH DẠNG
                  </p>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#164e63" }}
                    onClick={() => {
                      downloadTextFile(exportToGift(items), "quiz_moodle_gift.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📚 GIFT (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 4, background: "#1e3a8a" }}
                    onClick={() => {
                      downloadTextFile(exportToAiken(items), "quiz_moodle_aiken.txt");
                      setShowExportMenu(false);
                    }}
                  >
                    📝 Aiken (.txt) — Moodle
                  </button>
                  <button
                    className="qp-regen-btn"
                    style={{ display: "block", width: "100%", textAlign: "left", background: "#14532d" }}
                    onClick={() => {
                      downloadTextFile(exportToCsv(items), "quiz_kahoot.csv", "text/csv;charset=utf-8");
                      setShowExportMenu(false);
                    }}
                  >
                    🎮 CSV (.csv) — Kahoot / Quizizz
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

      </header>

      {/* Progress bar (only before submit) */}
      {!submitted && (
        <div className="qp-progress-wrap">
          <div className="qp-progress-bar-track">
            <div
              className="qp-progress-bar-fill"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="qp-progress-label">
            {answered}/{total} câu đã trả lời
          </span>
          <span className="qp-timer">⏱ Thời gian: {formatTimer(elapsed)}</span>
        </div>
      )}

      {/* Main content */}
      <div className="qp-content">
        {/* Score panel (after submit) */}
        {submitted && (
          <ScorePanel
            score={score}
            total={total}
            elapsed={elapsed}
            savedId={savedId}
            stats={stats}
            items={items}
            userAnswers={answers}
            onRetry={handleRetry}
            onBack={handleBack}
          />
        )}

        {/* Filter toggle (after submit) */}
        {submitted && items.some((item) => answers[item.id] !== item.correct_answer) && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 8 }}>
            <button
              className={`qp-filter-toggle${filterErrors ? " active" : ""}`}
              onClick={() => setFilterErrors((p) => !p)}
            >
              {filterErrors ? "🔍 Đang lọc lỗi" : "❌ Chỉ hiện câu sai"}
            </button>
          </div>
        )}

        {/* Question cards */}
        {visibleItems.map((item, idx) => (
          <div key={item.id} id={`quiz-card-${items.indexOf(item)}`}>
            <QuizCard
              item={item}
              index={items.indexOf(item)}
              userAnswer={answers[item.id]}
              submitted={submitted}
              expanded={activeCard === idx}
              onSelect={handleSelect}
              onToggleExpand={(i) => setActiveCard(activeCard === i ? null : i)}
            />
          </div>
        ))}

        {submitted && filterErrors && visibleItems.length === 0 && (
          <div style={{
            textAlign: "center",
            padding: "40px 20px",
            color: "#4ade80",
            fontSize: 16,
            fontWeight: 600,
          }}>
            🎉 Tuyệt vời! Bạn không có câu nào sai.
          </div>
        )}
      </div>

      {/* Submit bar */}
      {!submitted && (
        <div className="qp-submit-bar">
          <span className={`qp-submit-status${allAnswered ? " all-done" : ""}`}>
            {allAnswered
              ? `✓ Đã trả lời tất cả ${total} câu`
              : `⚠ Còn ${unanswered} câu chưa trả lời`}
          </span>
          <button
            className={`qp-submit-btn${allAnswered ? " all-answered" : ""}`}
            onClick={handleSubmit}
            disabled={answered === 0}
          >
            Nộp bài →
          </button>
        </div>
      )}
    </div>
  );
}
